import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pl' | 'ru' | 'uk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const translations = {
  pl: {
    // Header
    'header.services': 'Usługi',
    'header.benefits': 'Korzyści',
    'header.pricing': 'Cennik',
    'header.testimonials': 'Opinie',
    'header.contact': 'Kontakt',
    'header.consultation': 'Darmowa konsultacja',

    // Hero
    'hero.title': 'Oszczędzaj 3 godziny dziennie w swoim salonie piękności',
    'hero.subtitle': 'Automatyzacja która zwraca się w 1 tydzień',
    'hero.description': 'Automatyczne zapisy, przypomnienia SMS i zarządzanie klientami. Właściciele salonów oszczędzają 15+ godzin tygodniowo i zwiększają zyski o 30%.',
    'hero.cta': 'Otrzymaj darmową instalację',
    'hero.demo': 'Zobacz jak działa',
    'hero.integrates': 'Integruje się z:',

    // Problems
    'problems.title': 'Czy rozpoznajesz te',
    'problems.subtitle': 'problemy?',
    'problems.description': 'Właściciele salonów piękności w Polsce tracą średnio 2-3 godziny dziennie na rutynowe zadania, które można zautomatyzować.',
    'problems.phone.title': '2-3 godziny dziennie na telefony',
    'problems.phone.description': 'Ciągłe odbieranie telefonów przerywa pracę z klientami i obniża jakość usług. Jeden telefon co 15 minut przez cały dzień.',
    'problems.noshow.title': '30% klientów nie przychodzi',
    'problems.noshow.description': 'Bez przypomnienia 30% klientów zapomina o wizycie. Jeden zagubiony klient to strata 200+ zł miesięcznie.',
    'problems.schedule.title': 'Chaos w terminarzach',
    'problems.schedule.description': 'Podwójne rezerwacje, pomyłki w godzinach, zagubione notatki. Chaos w terminarzach kosztuje 500+ zł tygodniowo.',
    'problems.clients.title': 'Brak bazy stałych klientów',
    'problems.clients.description': 'Bez systemu śledzenia klientów tracisz możliwość budowania lojalności i zwiększania wartości życiowej klienta.',
    'problems.recognize': 'Rozpoznajesz te problemy?',
    'problems.solution': 'Mamy rozwiązanie, które oszczędzi Ci 15+ godzin tygodniowo i zwiększy zyski o 30%.',
    'problems.see_solution': 'Zobacz rozwiązanie',

    // Solutions
    'solutions.title': 'Jak automatyzacja',
    'solutions.subtitle': 'rozwiązuje problemy',
    'solutions.description': '5 kluczowych automatyzacji, które transformują Twój salon w nowoczesny biznes działający 24/7.',
    'solutions.booking.title': 'Automatyczne zapisy online',
    'solutions.booking.process': 'Klienci rezerwują przez Instagram, WhatsApp lub stronę. System automatycznie potwierdza i dodaje do kalendarza.',
    'solutions.booking.result': '90% mniej telefonów, 24/7 dostępność',
    'solutions.reminders.title': 'Inteligentne przypomnienia',
    'solutions.reminders.process': 'Automatyczne SMS/WhatsApp 24h i 2h przed wizytą. Klient potwierdza jednym kliknięciem.',
    'solutions.reminders.result': '70% mniej no-show, oszczędność 2h dziennie',
    'solutions.database.title': 'Baza klientów i historia',
    'solutions.database.process': 'Automatyczne zapisywanie danych, preferencji, historii wizyt i wydatków każdego klienta.',
    'solutions.database.result': '40% więcej stałych klientów',
    'solutions.reviews.title': 'Automatyczne opinie',
    'solutions.reviews.process': 'Po wizycie klient automatycznie otrzymuje prośbę o opinię na Google/Facebook.',
    'solutions.reviews.result': '300% więcej pozytywnych opinii',
    'solutions.analytics.title': 'Raporty i analityka',
    'solutions.analytics.process': 'Automatyczne raporty sprzedaży, najpopularniejsze usługi, analiza rentowności.',
    'solutions.analytics.result': 'Lepsze decyzje biznesowe, +30% zysku',
    'solutions.cta': 'Sprawdź jak to działa',

    // How it works
    'how.title': 'Jak to',
    'how.subtitle': 'działa?',
    'how.description': 'Prosty proces w 5 krokach. Od konsultacji do pełnej automatyzacji w 24 godziny.',
    'how.consultation.title': 'Darmowa analiza',
    'how.consultation.description': 'Analizujemy Twoje procesy i pokazujemy potencjał oszczędności.',
    'how.consultation.details': '30 minut przez telefon lub osobiście',
    'how.setup.title': 'Instalacja i konfiguracja',
    'how.setup.description': 'Instalujemy i konfigurujemy wszystkie automatyzacje pod Twój salon.',
    'how.setup.details': '2-4 godziny, wszystko robimy za Ciebie',
    'how.save.title': 'Szkolenie i wsparcie',
    'how.save.description': 'Pokazujemy jak korzystać z systemu i wspieramy przez pierwszy miesiąc.',
    'how.save.details': '30 minut szkolenia + 30 dni wsparcia',
    'how.start.title': 'Gotowy na automatyzację?',
    'how.start.description': 'Umów darmową konsultację i sprawdź ile możesz oszczędzić.',
    'how.start.cta': 'Umów darmową konsultację',

    // Results
    'results.title': 'Rezultaty naszych',
    'results.subtitle': 'klientów',
    'results.description': 'Konkretne wyniki z salonów, które już korzystają z automatyzacji.',
    'results.noshow': 'mniej no-show',
    'results.noshow.description': 'Automatyczne przypomnienia redukują niestawiennictwo z 30% do 5%',
    'results.time': 'godziny oszczędności',
    'results.time.description': 'Dziennie więcej czasu na klientów i rozwój salonu',
    'results.bookings': 'więcej rezerwacji',
    'results.bookings.description': 'Dostępność 24/7 zwiększa liczbę rezerwacji o 30%',
    'results.profit': 'więcej zysku',
    'results.profit.description': 'Miesięcznie dzięki lepszej organizacji i większej liczbie klientów',
    'results.roi.title': 'Automatyzacja zwraca się w 1 tydzień',
    'results.roi.description': 'Średni salon oszczędza 1800 zł miesięcznie na czasie pracy. Koszt automatyzacji: 400€ + 50€/miesiąc.',
    'results.roi.cta': 'Oblicz swoją oszczędność',

    // Calculator
    'calculator.title': 'Oblicz swoją',
    'calculator.subtitle': 'oszczędność',
    'calculator.description': 'Sprawdź ile czasu i pieniędzy oszczędzisz dzięki automatyzacji w swoim salonie.',
    'calculator.params': 'Parametry Twojego salonu',
    'calculator.appointments': 'Wizyt dziennie:',
    'calculator.time': 'Minut na wizytę (telefon + notatki):',
    'calculator.rate': 'Twoja stawka godzinowa:',
    'calculator.savings': 'Twoja oszczędność',
    'calculator.daily': 'dziennie',
    'calculator.monthly': 'miesięcznie',
    'calculator.payback': 'Zwrot inwestycji w',
    'calculator.payback.week': 'tydzień',
    'calculator.payback.weeks': 'tygodni',
    'calculator.payback.then': 'Potem sama oszczędność!',
    'calculator.cta': 'Zacznij oszczędzać',
    'min': 'min',
    'monthly': 'miesięcznie',

    // Pricing
    'pricing.title': 'Jedna cena,',
    'pricing.subtitle': 'wszystko',
    'pricing.all_included': 'włączone',
    'pricing.description': 'Przejrzysta cena bez ukrytych kosztów. Porównaj z konkurencją i zobacz różnicę.',
    'pricing.special': 'OFERTA WPROWADZAJĄCA',
    'pricing.standard': 'Standardowa cena',
    'pricing.setup': 'instalacja',
    'pricing.monthly': 'Miesięczne wsparcie i aktualizacje',
    'pricing.includes': 'Co otrzymujesz',
    'pricing.feature1': 'Automatyczne zapisy z Instagram/WhatsApp/strony',
    'pricing.feature2': 'Inteligentne przypomnienia SMS/WhatsApp',
    'pricing.feature3': 'Baza klientów z historią wizyt',
    'pricing.feature4': 'Automatyczne prośby o opinie',
    'pricing.feature5': 'Raporty sprzedaży i analityka',
    'pricing.feature6': 'Integracja z popularnymi kalendarzami',
    'pricing.feature7': 'Wsparcie techniczne 24/7',
    'pricing.bonuses': 'Bonusy dla pierwszych 50 salonów',
    'pricing.bonus1': 'Darmowa instalacja (wartość €200)',
    'pricing.bonus2': 'Bezpłatne szkolenie zespołu (wartość €150)',
    'pricing.bonus3': 'Pierwszy miesiąc wsparcia gratis',
    'pricing.cta': 'Zarezerwuj swoją automatyzację',
    'pricing.guarantee1': '30 dni gwarancji',
    'pricing.guarantee1.desc': 'Nie jesteś zadowolony? Zwracamy pieniądze',
    'pricing.guarantee2': 'Instalacja w 24h',
    'pricing.guarantee2.desc': 'Szybka implementacja bez przestojów',
    'pricing.guarantee3': 'Bezpłatne wsparcie',
    'pricing.guarantee3.desc': 'Pierwszy miesiąc wsparcia technicznego gratis',

    // Testimonials
    'testimonials.title': 'Co mówią właściciele',
    'testimonials.subtitle': 'salonów',
    'testimonials.description': 'Prawdziwe opinie od salonów, które już korzystają z automatyzacji.',
    'testimonials.1.name': 'Anna Kowalska',
    'testimonials.1.salon': 'Salon Anna, Kraków',
    'testimonials.1.text': 'W pierwszy miesiąc no-show spadło z 30% do 5%. Oszczędzam 3 godziny dziennie, które teraz mogę poświęcić klientom. Automatyzacja zwróciła się w tydzień!',
    'testimonials.2.name': 'Marta Nowak',
    'testimonials.2.salon': 'Beauty Studio, Wrocław',
    'testimonials.2.text': 'Klienci uwielbiają rezerwować przez Instagram. Mam 40% więcej stałych klientów i w końcu mogę się skupić na tym co kocham - pracy z klientami.',
    'testimonials.3.name': 'Katarzyna Wiśniewska',
    'testimonials.3.salon': 'Glow Salon, Warszawa',
    'testimonials.3.text': 'Automatyczne przypomnienia to game changer. Zarabiam 500 zł więcej miesięcznie tylko dlatego, że klienci nie zapominają o wizytach.',
    'testimonials.integrations': 'Integruje się z popularnymi platformami',
    'testimonials.others': 'I wieloma innymi...',

    // FAQ
    'faq.title': 'Często zadawane',
    'faq.subtitle': 'pytania',
    'faq.description': 'Odpowiedzi na najczęstsze pytania o automatyzację salonów piękności.',
    'faq.1.question': 'Czy €400 + €50/miesiąc to nie za drogo?',
    'faq.1.answer': 'To kosztuje mniej niż 2 fryzury, a oszczędza 60 godzin miesięcznie. Średni salon zwraca inwestycję w pierwszy tydzień dzięki oszczędności czasu i mniejszej liczbie no-show.',
    'faq.2.question': 'Czy to nie jest zbyt skomplikowane?',
    'faq.2.answer': 'Wcale nie! Konfiguracja trwa 24 godziny i robimy wszystko za Ciebie. Obsługa jest tak prosta jak WhatsApp. Dodatkowo otrzymujesz bezpłatne szkolenie.',
    'faq.3.question': 'Co jeśli nie będę umiał/a korzystać?',
    'faq.3.answer': 'Zapewniamy bezpłatne szkolenie dla Ciebie i Twojego zespołu oraz 30 dni pełnego wsparcia technicznego. Jesteśmy dostępni 24/7.',
    'faq.4.question': 'Czy działa z moim obecnym systemem?',
    'faq.4.answer': 'Tak! Integrujemy się z popularnymi kalendarzami (Google, Outlook), platformami rezerwacyjnymi (Booksy, Fresha) i mediami społecznościowymi.',
    'faq.5.question': 'Co jeśli nie będę zadowolony/a?',
    'faq.5.answer': 'Oferujemy 30-dniową gwarancję zwrotu pieniędzy. Jeśli nie jesteś zadowolony z rezultatów, zwracamy całą kwotę.',
    'faq.6.question': 'Jak szybko zobaczę rezultaty?',
    'faq.6.answer': 'Pierwsze rezultaty widać już po 24 godzinach od instalacji. Pełne korzyści (mniej no-show, więcej czasu) odczujesz w ciągu pierwszego tygodnia.',
    'faq.more.title': 'Masz więcej pytań?',
    'faq.more.description': 'Skontaktuj się z nami - odpowiemy na wszystkie Twoje wątpliwości.',
    'faq.call': 'Zadzwoń teraz',
    'faq.whatsapp': 'Napisz na WhatsApp',

    // Contact
    'contact.title': 'Umów darmową',
    'contact.subtitle': 'konsultację',
    'contact.description': 'Sprawdzimy Twój salon i pokażemy dokładnie ile możesz oszczędzić. Konsultacja trwa 30 minut i jest całkowicie bezpłatna.',
    'contact.name': 'Imię',
    'contact.name.placeholder': 'Twoje imię',
    'contact.phone': 'Telefon',
    'contact.phone.placeholder': '+48 123 456 789',
    'contact.salon': 'Nazwa salonu',
    'contact.salon.placeholder': 'Nazwa Twojego salonu',
    'contact.city': 'Miasto',
    'contact.city.placeholder': 'Warszawa',
    'contact.comment': 'Dodatkowe informacje',
    'contact.comment.placeholder': 'Opisz swój salon, ile masz klientów dziennie...',
    'contact.submit': 'Umów darmową konsultację',
    'contact.guarantees': 'Nasze gwarancje',
    'contact.guarantee1': 'Konsultacja 100% bezpłatna',
    'contact.guarantee2': 'Oddzwaniamy w 15 minut',
    'contact.guarantee3': 'Bez zobowiązań',
    'contact.callback': 'Oddzwonimy w 15 minut',
    'contact.callback.desc': 'Nasz ekspert skontaktuje się z Tobą w ciągu 15 minut i umówi dogodny termin konsultacji.',
    'contact.questions': 'Masz pilne pytania?',
    'contact.hours': 'Pon-Pt 9:00-18:00, Sob 10:00-14:00',
    'contact.success.bonus': 'Bonus: Otrzymasz bezpłatny audit swojego salonu (wartość €100)!',

    // Footer
    'footer.description': 'Automatyzacja procesów dla salonów piękności. Oszczędzaj czas, zwiększaj zyski.',
    'footer.links': 'Szybkie linki',
    'footer.contact': 'Kontakt',
    'footer.hours': 'Godziny pracy',
    'footer.hours.weekdays': 'Pon-Pt: 9:00-18:00',
    'footer.hours.saturday': 'Sobota: 10:00-14:00',
    'footer.hours.sunday': 'Niedziela: Zamknięte',
    'footer.consultation': 'Darmowa konsultacja dostępna!',
    'footer.copyright': '© 2025 Beauty Automation. Wszystkie prawa zastrzeżone.',
    'footer.privacy': 'Polityka prywatności',
    'footer.terms': 'Regulamin',

    // WhatsApp
    'whatsapp.message': 'Cześć! Chciałbym/chciałabym dowiedzieć się więcej o automatyzacji dla mojego salonu piękności.'
  },
  
  ru: {
    // Header
    'header.services': 'Услуги',
    'header.benefits': 'Преимущества',
    'header.pricing': 'Цены',
    'header.testimonials': 'Отзывы',
    'header.contact': 'Контакт',
    'header.consultation': 'Бесплатная консультация',

    // Hero
    'hero.title': 'Экономьте 3 часа в день в своем салоне красоты',
    'hero.subtitle': 'Автоматизация окупается за 1 неделю',
    'hero.description': 'Автоматические записи, SMS-напоминания и управление клиентами. Владельцы салонов экономят 15+ часов в неделю и увеличивают прибыль на 30%.',
    'hero.cta': 'Получить бесплатную установку',
    'hero.demo': 'Посмотреть как работает',
    'hero.integrates': 'Интегрируется с:',

    // Problems
    'problems.title': 'Узнаете эти',
    'problems.subtitle': 'проблемы?',
    'problems.description': 'Владельцы салонов красоты в Польше тратят в среднем 2-3 часа в день на рутинные задачи, которые можно автоматизировать.',
    'problems.phone.title': '2-3 часа в день на телефоны',
    'problems.phone.description': 'Постоянные звонки прерывают работу с клиентами и снижают качество услуг. Один звонок каждые 15 минут весь день.',
    'problems.noshow.title': '30% клиентов не приходят',
    'problems.noshow.description': 'Без напоминания 30% клиентов забывают о визите. Один потерянный клиент - это потеря 200+ злотых в месяц.',
    'problems.schedule.title': 'Хаос в расписании',
    'problems.schedule.description': 'Двойные бронирования, ошибки во времени, потерянные заметки. Хаос в расписании стоит 500+ злотых в неделю.',
    'problems.clients.title': 'Нет базы постоянных клиентов',
    'problems.clients.description': 'Без системы отслеживания клиентов вы теряете возможность строить лояльность и увеличивать жизненную ценность клиента.',
    'problems.recognize': 'Узнаете эти проблемы?',
    'problems.solution': 'У нас есть решение, которое сэкономит вам 15+ часов в неделю и увеличит прибыль на 30%.',
    'problems.see_solution': 'Посмотреть решение',

    // Solutions
    'solutions.title': 'Как автоматизация',
    'solutions.subtitle': 'решает проблемы',
    'solutions.description': '5 ключевых автоматизаций, которые превращают ваш салон в современный бизнес, работающий 24/7.',
    'solutions.booking.title': 'Автоматические онлайн-записи',
    'solutions.booking.process': 'Клиенты бронируют через Instagram, WhatsApp или сайт. Система автоматически подтверждает и добавляет в календарь.',
    'solutions.booking.result': '90% меньше звонков, доступность 24/7',
    'solutions.reminders.title': 'Умные напоминания',
    'solutions.reminders.process': 'Автоматические SMS/WhatsApp за 24ч и 2ч до визита. Клиент подтверждает одним кликом.',
    'solutions.reminders.result': '70% меньше no-show, экономия 2ч в день',
    'solutions.database.title': 'База клиентов и история',
    'solutions.database.process': 'Автоматическое сохранение данных, предпочтений, истории визитов и трат каждого клиента.',
    'solutions.database.result': '40% больше постоянных клиентов',
    'solutions.reviews.title': 'Автоматические отзывы',
    'solutions.reviews.process': 'После визита клиент автоматически получает просьбу об отзыве в Google/Facebook.',
    'solutions.reviews.result': '300% больше положительных отзывов',
    'solutions.analytics.title': 'Отчеты и аналитика',
    'solutions.analytics.process': 'Автоматические отчеты продаж, популярные услуги, анализ рентабельности.',
    'solutions.analytics.result': 'Лучшие бизнес-решения, +30% прибыли',
    'solutions.cta': 'Посмотреть как это работает',

    // How it works
    'how.title': 'Как это',
    'how.subtitle': 'работает?',
    'how.description': 'Простой процесс в 5 шагов. От консультации до полной автоматизации за 24 часа.',
    'how.consultation.title': 'Бесплатный анализ',
    'how.consultation.description': 'Анализируем ваши процессы и показываем потенциал экономии.',
    'how.consultation.details': '30 минут по телефону или лично',
    'how.setup.title': 'Установка и настройка',
    'how.setup.description': 'Устанавливаем и настраиваем все автоматизации под ваш салон.',
    'how.setup.details': '2-4 часа, все делаем за вас',
    'how.save.title': 'Обучение и поддержка',
    'how.save.description': 'Показываем как пользоваться системой и поддерживаем первый месяц.',
    'how.save.details': '30 минут обучения + 30 дней поддержки',
    'how.start.title': 'Готовы к автоматизации?',
    'how.start.description': 'Запишитесь на бесплатную консультацию и узнайте сколько можете сэкономить.',
    'how.start.cta': 'Записаться на консультацию',

    // Results
    'results.title': 'Результаты наших',
    'results.subtitle': 'клиентов',
    'results.description': 'Конкретные результаты салонов, которые уже используют автоматизацию.',
    'results.noshow': 'меньше no-show',
    'results.noshow.description': 'Автоматические напоминания снижают неявку с 30% до 5%',
    'results.time': 'часа экономии',
    'results.time.description': 'В день больше времени на клиентов и развитие салона',
    'results.bookings': 'больше бронирований',
    'results.bookings.description': 'Доступность 24/7 увеличивает количество бронирований на 30%',
    'results.profit': 'больше прибыли',
    'results.profit.description': 'В месяц благодаря лучшей организации и большему количеству клиентов',
    'results.roi.title': 'Автоматизация окупается за 1 неделю',
    'results.roi.description': 'Средний салон экономит 1800 злотых в месяц на рабочем времени. Стоимость автоматизации: 400€ + 50€/месяц.',
    'results.roi.cta': 'Рассчитать свою экономию',

    // Calculator
    'calculator.title': 'Рассчитайте свою',
    'calculator.subtitle': 'экономию',
    'calculator.description': 'Узнайте сколько времени и денег сэкономите благодаря автоматизации в своем салоне.',
    'calculator.params': 'Параметры вашего салона',
    'calculator.appointments': 'Визитов в день:',
    'calculator.time': 'Минут на визит (телефон + заметки):',
    'calculator.rate': 'Ваша часовая ставка:',
    'calculator.savings': 'Ваша экономия',
    'calculator.daily': 'в день',
    'calculator.monthly': 'в месяц',
    'calculator.payback': 'Окупаемость за',
    'calculator.payback.week': 'неделю',
    'calculator.payback.weeks': 'недель',
    'calculator.payback.then': 'Потом чистая экономия!',
    'calculator.cta': 'Начать экономить',
    'min': 'мин',
    'monthly': 'в месяц',

    // Pricing
    'pricing.title': 'Одна цена,',
    'pricing.subtitle': 'все',
    'pricing.all_included': 'включено',
    'pricing.description': 'Прозрачная цена без скрытых расходов. Сравните с конкурентами и увидьте разницу.',
    'pricing.special': 'ВВОДНОЕ ПРЕДЛОЖЕНИЕ',
    'pricing.standard': 'Стандартная цена',
    'pricing.setup': 'установка',
    'pricing.monthly': 'Ежемесячная поддержка и обновления',
    'pricing.includes': 'Что вы получаете',
    'pricing.feature1': 'Автоматические записи с Instagram/WhatsApp/сайта',
    'pricing.feature2': 'Умные напоминания SMS/WhatsApp',
    'pricing.feature3': 'База клиентов с историей визитов',
    'pricing.feature4': 'Автоматические просьбы об отзывах',
    'pricing.feature5': 'Отчеты продаж и аналитика',
    'pricing.feature6': 'Интеграция с популярными календарями',
    'pricing.feature7': 'Техническая поддержка 24/7',
    'pricing.bonuses': 'Бонусы для первых 50 салонов',
    'pricing.bonus1': 'Бесплатная установка (стоимость €200)',
    'pricing.bonus2': 'Бесплатное обучение команды (стоимость €150)',
    'pricing.bonus3': 'Первый месяц поддержки бесплатно',
    'pricing.cta': 'Забронировать автоматизацию',
    'pricing.guarantee1': '30 дней гарантии',
    'pricing.guarantee1.desc': 'Не довольны? Возвращаем деньги',
    'pricing.guarantee2': 'Установка за 24ч',
    'pricing.guarantee2.desc': 'Быстрое внедрение без простоев',
    'pricing.guarantee3': 'Бесплатная поддержка',
    'pricing.guarantee3.desc': 'Первый месяц технической поддержки бесплатно',

    // Testimonials
    'testimonials.title': 'Что говорят владельцы',
    'testimonials.subtitle': 'салонов',
    'testimonials.description': 'Настоящие отзывы от салонов, которые уже используют автоматизацию.',
    'testimonials.1.name': 'Анна Ковальская',
    'testimonials.1.salon': 'Салон Анна, Краков',
    'testimonials.1.text': 'В первый месяц no-show упало с 30% до 5%. Экономлю 3 часа в день, которые теперь могу посвятить клиентам. Автоматизация окупилась за неделю!',
    'testimonials.2.name': 'Марта Новак',
    'testimonials.2.salon': 'Beauty Studio, Вроцлав',
    'testimonials.2.text': 'Клиенты обожают бронировать через Instagram. У меня на 40% больше постоянных клиентов и наконец могу сосредоточиться на том что люблю - работе с клиентами.',
    'testimonials.3.name': 'Катажина Вишневская',
    'testimonials.3.salon': 'Glow Salon, Варшава',
    'testimonials.3.text': 'Автоматические напоминания - это game changer. Зарабатываю на 500 злотых больше в месяц только потому, что клиенты не забывают о визитах.',
    'testimonials.integrations': 'Интегрируется с популярными платформами',
    'testimonials.others': 'И многими другими...',

    // FAQ
    'faq.title': 'Часто задаваемые',
    'faq.subtitle': 'вопросы',
    'faq.description': 'Ответы на самые частые вопросы об автоматизации салонов красоты.',
    'faq.1.question': 'Не слишком ли дорого €400 + €50/месяц?',
    'faq.1.answer': 'Это стоит меньше чем 2 стрижки, а экономит 60 часов в месяц. Средний салон окупает инвестицию в первую неделю благодаря экономии времени и меньшему количеству no-show.',
    'faq.2.question': 'Не слишком ли это сложно?',
    'faq.2.answer': 'Совсем нет! Настройка занимает 24 часа и мы делаем все за вас. Использование простое как WhatsApp. Плюс вы получаете бесплатное обучение.',
    'faq.3.question': 'Что если я не смогу пользоваться?',
    'faq.3.answer': 'Мы предоставляем бесплатное обучение для вас и вашей команды плюс 30 дней полной технической поддержки. Мы доступны 24/7.',
    'faq.4.question': 'Работает ли с моей текущей системой?',
    'faq.4.answer': 'Да! Мы интегрируемся с популярными календарями (Google, Outlook), платформами бронирования (Booksy, Fresha) и социальными сетями.',
    'faq.5.question': 'Что если я не буду доволен?',
    'faq.5.answer': 'Мы предлагаем 30-дневную гарантию возврата денег. Если вы не довольны результатами, возвращаем всю сумму.',
    'faq.6.question': 'Как быстро увижу результаты?',
    'faq.6.answer': 'Первые результаты видны уже через 24 часа после установки. Полные преимущества (меньше no-show, больше времени) почувствуете в течение первой недели.',
    'faq.more.title': 'Есть еще вопросы?',
    'faq.more.description': 'Свяжитесь с нами - ответим на все ваши сомнения.',
    'faq.call': 'Позвонить сейчас',
    'faq.whatsapp': 'Написать в WhatsApp',

    // Contact
    'contact.title': 'Записаться на бесплатную',
    'contact.subtitle': 'консультацию',
    'contact.description': 'Проверим ваш салон и покажем точно сколько можете сэкономить. Консультация длится 30 минут и полностью бесплатна.',
    'contact.name': 'Имя',
    'contact.name.placeholder': 'Ваше имя',
    'contact.phone': 'Телефон',
    'contact.phone.placeholder': '+48 123 456 789',
    'contact.salon': 'Название салона',
    'contact.salon.placeholder': 'Название вашего салона',
    'contact.city': 'Город',
    'contact.city.placeholder': 'Варшава',
    'contact.comment': 'Дополнительная информация',
    'contact.comment.placeholder': 'Опишите свой салон, сколько клиентов в день...',
    'contact.submit': 'Записаться на консультацию',
    'contact.guarantees': 'Наши гарантии',
    'contact.guarantee1': 'Консультация 100% бесплатна',
    'contact.guarantee2': 'Перезвоним через 15 минут',
    'contact.guarantee3': 'Без обязательств',
    'contact.callback': 'Перезвоним через 15 минут',
    'contact.callback.desc': 'Наш эксперт свяжется с вами в течение 15 минут и назначит удобное время консультации.',
    'contact.questions': 'Есть срочные вопросы?',
    'contact.hours': 'Пн-Пт 9:00-18:00, Сб 10:00-14:00',
    'contact.success.bonus': 'Бонус: Получите бесплатный аудит своего салона (стоимость €100)!',

    // Footer
    'footer.description': 'Автоматизация процессов для салонов красоты. Экономьте время, увеличивайте прибыль.',
    'footer.links': 'Быстрые ссылки',
    'footer.contact': 'Контакт',
    'footer.hours': 'Часы работы',
    'footer.hours.weekdays': 'Пн-Пт: 9:00-18:00',
    'footer.hours.saturday': 'Суббота: 10:00-14:00',
    'footer.hours.sunday': 'Воскресенье: Закрыто',
    'footer.consultation': 'Бесплатная консультация доступна!',
    'footer.copyright': '© 2025 Beauty Automation. Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',

    // WhatsApp
    'whatsapp.message': 'Привет! Хотел бы узнать больше об автоматизации для моего салона красоты.'
  },

  uk: {
    // Header
    'header.services': 'Послуги',
    'header.benefits': 'Переваги',
    'header.pricing': 'Ціни',
    'header.testimonials': 'Відгуки',
    'header.contact': 'Контакт',
    'header.consultation': 'Безкоштовна консультація',

    // Hero
    'hero.title': 'Економте 3 години на день у своєму салоні краси',
    'hero.subtitle': 'Автоматизація окупається за 1 тиждень',
    'hero.description': 'Автоматичні записи, SMS-нагадування та управління клієнтами. Власники салонів економлять 15+ годин на тиждень та збільшують прибуток на 30%.',
    'hero.cta': 'Отримати безкоштовну установку',
    'hero.demo': 'Подивитися як працює',
    'hero.integrates': 'Інтегрується з:',

    // Problems
    'problems.title': 'Впізнаєте ці',
    'problems.subtitle': 'проблеми?',
    'problems.description': 'Власники салонів краси в Польщі витрачають в середньому 2-3 години на день на рутинні завдання, які можна автоматизувати.',
    'problems.phone.title': '2-3 години на день на телефони',
    'problems.phone.description': 'Постійні дзвінки переривають роботу з клієнтами та знижують якість послуг. Один дзвінок кожні 15 хвилин весь день.',
    'problems.noshow.title': '30% клієнтів не приходять',
    'problems.noshow.description': 'Без нагадування 30% клієнтів забувають про візит. Один втрачений клієнт - це втрата 200+ злотих на місяць.',
    'problems.schedule.title': 'Хаос у розкладі',
    'problems.schedule.description': 'Подвійні бронювання, помилки в часі, загублені нотатки. Хаос у розкладі коштує 500+ злотих на тиждень.',
    'problems.clients.title': 'Немає бази постійних клієнтів',
    'problems.clients.description': 'Без системи відстеження клієнтів ви втрачаєте можливість будувати лояльність та збільшувати життєву цінність клієнта.',
    'problems.recognize': 'Впізнаєте ці проблеми?',
    'problems.solution': 'У нас є рішення, яке заощадить вам 15+ годин на тиждень та збільшить прибуток на 30%.',
    'problems.see_solution': 'Подивитися рішення',

    // Solutions
    'solutions.title': 'Як автоматизація',
    'solutions.subtitle': 'вирішує проблеми',
    'solutions.description': '5 ключових автоматизацій, які перетворюють ваш салон на сучасний бізнес, що працює 24/7.',
    'solutions.booking.title': 'Автоматичні онлайн-записи',
    'solutions.booking.process': 'Клієнти бронюють через Instagram, WhatsApp або сайт. Система автоматично підтверджує та додає до календаря.',
    'solutions.booking.result': '90% менше дзвінків, доступність 24/7',
    'solutions.reminders.title': 'Розумні нагадування',
    'solutions.reminders.process': 'Автоматичні SMS/WhatsApp за 24г та 2г до візиту. Клієнт підтверджує одним кліком.',
    'solutions.reminders.result': '70% менше no-show, економія 2г на день',
    'solutions.database.title': 'База клієнтів та історія',
    'solutions.database.process': 'Автоматичне збереження даних, уподобань, історії візитів та витрат кожного клієнта.',
    'solutions.database.result': '40% більше постійних клієнтів',
    'solutions.reviews.title': 'Автоматичні відгуки',
    'solutions.reviews.process': 'Після візиту клієнт автоматично отримує прохання про відгук у Google/Facebook.',
    'solutions.reviews.result': '300% більше позитивних відгуків',
    'solutions.analytics.title': 'Звіти та аналітика',
    'solutions.analytics.process': 'Автоматичні звіти продажів, популярні послуги, аналіз рентабельності.',
    'solutions.analytics.result': 'Кращі бізнес-рішення, +30% прибутку',
    'solutions.cta': 'Подивитися як це працює',

    // How it works
    'how.title': 'Як це',
    'how.subtitle': 'працює?',
    'how.description': 'Простий процес у 5 кроків. Від консультації до повної автоматизації за 24 години.',
    'how.consultation.title': 'Безкоштовний аналіз',
    'how.consultation.description': 'Аналізуємо ваші процеси та показуємо потенціал економії.',
    'how.consultation.details': '30 хвилин по телефону або особисто',
    'how.setup.title': 'Установка та налаштування',
    'how.setup.description': 'Встановлюємо та налаштовуємо всі автоматизації під ваш салон.',
    'how.setup.details': '2-4 години, все робимо за вас',
    'how.save.title': 'Навчання та підтримка',
    'how.save.description': 'Показуємо як користуватися системою та підтримуємо перший місяць.',
    'how.save.details': '30 хвилин навчання + 30 днів підтримки',
    'how.start.title': 'Готові до автоматизації?',
    'how.start.description': 'Запишіться на безкоштовну консультацію та дізнайтеся скільки можете заощадити.',
    'how.start.cta': 'Записатися на консультацію',

    // Results
    'results.title': 'Результати наших',
    'results.subtitle': 'клієнтів',
    'results.description': 'Конкретні результати салонів, які вже використовують автоматизацію.',
    'results.noshow': 'менше no-show',
    'results.noshow.description': 'Автоматичні нагадування знижують неявку з 30% до 5%',
    'results.time': 'години економії',
    'results.time.description': 'На день більше часу на клієнтів та розвиток салону',
    'results.bookings': 'більше бронювань',
    'results.bookings.description': 'Доступність 24/7 збільшує кількість бронювань на 30%',
    'results.profit': 'більше прибутку',
    'results.profit.description': 'На місяць завдяки кращій організації та більшій кількості клієнтів',
    'results.roi.title': 'Автоматизація окупається за 1 тиждень',
    'results.roi.description': 'Середній салон економить 1800 злотих на місяць на робочому часі. Вартість автоматизації: 400€ + 50€/місяць.',
    'results.roi.cta': 'Розрахувати свою економію',

    // Calculator
    'calculator.title': 'Розрахуйте свою',
    'calculator.subtitle': 'економію',
    'calculator.description': 'Дізнайтеся скільки часу та грошей заощадите завдяки автоматизації у своєму салоні.',
    'calculator.params': 'Параметри вашого салону',
    'calculator.appointments': 'Візитів на день:',
    'calculator.time': 'Хвилин на візит (телефон + нотатки):',
    'calculator.rate': 'Ваша годинна ставка:',
    'calculator.savings': 'Ваша економія',
    'calculator.daily': 'на день',
    'calculator.monthly': 'на місяць',
    'calculator.payback': 'Окупність за',
    'calculator.payback.week': 'тиждень',
    'calculator.payback.weeks': 'тижнів',
    'calculator.payback.then': 'Потім чиста економія!',
    'calculator.cta': 'Почати економити',
    'min': 'хв',
    'monthly': 'на місяць',

    // Pricing
    'pricing.title': 'Одна ціна,',
    'pricing.subtitle': 'все',
    'pricing.all_included': 'включено',
    'pricing.description': 'Прозора ціна без прихованих витрат. Порівняйте з конкурентами та побачте різницю.',
    'pricing.special': 'ВСТУПНА ПРОПОЗИЦІЯ',
    'pricing.standard': 'Стандартна ціна',
    'pricing.setup': 'установка',
    'pricing.monthly': 'Щомісячна підтримка та оновлення',
    'pricing.includes': 'Що ви отримуєте',
    'pricing.feature1': 'Автоматичні записи з Instagram/WhatsApp/сайту',
    'pricing.feature2': 'Розумні нагадування SMS/WhatsApp',
    'pricing.feature3': 'База клієнтів з історією візитів',
    'pricing.feature4': 'Автоматичні прохання про відгуки',
    'pricing.feature5': 'Звіти продажів та аналітика',
    'pricing.feature6': 'Інтеграція з популярними календарями',
    'pricing.feature7': 'Технічна підтримка 24/7',
    'pricing.bonuses': 'Бонуси для перших 50 салонів',
    'pricing.bonus1': 'Безкоштовна установка (вартість €200)',
    'pricing.bonus2': 'Безкоштовне навчання команди (вартість €150)',
    'pricing.bonus3': 'Перший місяць підтримки безкоштовно',
    'pricing.cta': 'Забронювати автоматизацію',
    'pricing.guarantee1': '30 днів гарантії',
    'pricing.guarantee1.desc': 'Не задоволені? Повертаємо гроші',
    'pricing.guarantee2': 'Установка за 24г',
    'pricing.guarantee2.desc': 'Швидке впровадження без простоїв',
    'pricing.guarantee3': 'Безкоштовна підтримка',
    'pricing.guarantee3.desc': 'Перший місяць технічної підтримки безкоштовно',

    // Testimonials
    'testimonials.title': 'Що кажуть власники',
    'testimonials.subtitle': 'салонів',
    'testimonials.description': 'Справжні відгуки від салонів, які вже використовують автоматизацію.',
    'testimonials.1.name': 'Анна Ковальська',
    'testimonials.1.salon': 'Салон Анна, Краків',
    'testimonials.1.text': 'У перший місяць no-show впало з 30% до 5%. Економлю 3 години на день, які тепер можу присвятити клієнтам. Автоматизація окупилася за тиждень!',
    'testimonials.2.name': 'Марта Новак',
    'testimonials.2.salon': 'Beauty Studio, Вроцлав',
    'testimonials.2.text': 'Клієнти обожнюють бронювати через Instagram. У мене на 40% більше постійних клієнтів і нарешті можу зосередитися на тому що люблю - роботі з клієнтами.',
    'testimonials.3.name': 'Катажина Вишневська',
    'testimonials.3.salon': 'Glow Salon, Варшава',
    'testimonials.3.text': 'Автоматичні нагадування - це game changer. Заробляю на 500 злотих більше на місяць тільки тому, що клієнти не забувають про візити.',
    'testimonials.integrations': 'Інтегрується з популярними платформами',
    'testimonials.others': 'І багатьма іншими...',

    // FAQ
    'faq.title': 'Часто задавані',
    'faq.subtitle': 'питання',
    'faq.description': 'Відповіді на найчастіші питання про автоматизацію салонів краси.',
    'faq.1.question': 'Чи не занадто дорого €400 + €50/місяць?',
    'faq.1.answer': 'Це коштує менше ніж 2 стрижки, а економить 60 годин на місяць. Середній салон окупає інвестицію в перший тиждень завдяки економії часу та меншій кількості no-show.',
    'faq.2.question': 'Чи не занадто це складно?',
    'faq.2.answer': 'Зовсім ні! Налаштування займає 24 години і ми робимо все за вас. Використання просте як WhatsApp. Плюс ви отримуєте безкоштовне навчання.',
    'faq.3.question': 'Що якщо я не зможу користуватися?',
    'faq.3.answer': 'Ми надаємо безкоштовне навчання для вас та вашої команди плюс 30 днів повної технічної підтримки. Ми доступні 24/7.',
    'faq.4.question': 'Чи працює з моєю поточною системою?',
    'faq.4.answer': 'Так! Ми інтегруємося з популярними календарями (Google, Outlook), платформами бронювання (Booksy, Fresha) та соціальними мережами.',
    'faq.5.question': 'Що якщо я не буду задоволений?',
    'faq.5.answer': 'Ми пропонуємо 30-денну гарантію повернення грошей. Якщо ви не задоволені результатами, повертаємо всю суму.',
    'faq.6.question': 'Як швидко побачу результати?',
    'faq.6.answer': 'Перші результати видно вже через 24 години після установки. Повні переваги (менше no-show, більше часу) відчуєте протягом першого тижня.',
    'faq.more.title': 'Є ще питання?',
    'faq.more.description': "Зв'яжіться з нами - відповімо на всі ваші сумніви.",
    'faq.call': 'Подзвонити зараз',
    'faq.whatsapp': 'Написати в WhatsApp',

    // Contact
    'contact.title': 'Записатися на безкоштовну',
    'contact.subtitle': 'консультацію',
    'contact.description': 'Перевіримо ваш салон та покажемо точно скільки можете заощадити. Консультація триває 30 хвилин та повністю безкоштовна.',
    'contact.name': "Ім'я",
    'contact.name.placeholder': "Ваше ім'я",
    'contact.phone': 'Телефон',
    'contact.phone.placeholder': '+48 123 456 789',
    'contact.salon': 'Назва салону',
    'contact.salon.placeholder': 'Назва вашого салону',
    'contact.city': 'Місто',
    'contact.city.placeholder': 'Варшава',
    'contact.comment': 'Додаткова інформація',
    'contact.comment.placeholder': 'Опишіть свій салон, скільки клієнтів на день...',
    'contact.submit': 'Записатися на консультацію',
    'contact.guarantees': 'Наші гарантії',
    'contact.guarantee1': 'Консультація 100% безкоштовна',
    'contact.guarantee2': 'Передзвонимо через 15 хвилин',
    'contact.guarantee3': "Без зобов'язань",
    'contact.callback': 'Передзвонимо через 15 хвилин',
    'contact.callback.desc': "Наш експерт зв'яжеться з вами протягом 15 хвилин та призначить зручний час консультації.",
    'contact.questions': 'Є термінові питання?',
    'contact.hours': 'Пн-Пт 9:00-18:00, Сб 10:00-14:00',
    'contact.success.bonus': 'Бонус: Отримайте безкоштовний аудит свого салону (вартість €100)!',

    // Footer
    'footer.description': 'Автоматизація процесів для салонів краси. Економте час, збільшуйте прибуток.',
    'footer.links': 'Швидкі посилання',
    'footer.contact': 'Контакт',
    'footer.hours': 'Години роботи',
    'footer.hours.weekdays': 'Пн-Пт: 9:00-18:00',
    'footer.hours.saturday': 'Субота: 10:00-14:00',
    'footer.hours.sunday': 'Неділя: Зачинено',
    'footer.consultation': 'Безкоштовна консультація доступна!',
    'footer.copyright': '© 2025 Beauty Automation. Всі права захищені.',
    'footer.privacy': 'Політика конфіденційності',
    'footer.terms': 'Умови використання',

    // WhatsApp
    'whatsapp.message': 'Привіт! Хотів би дізнатися більше про автоматизацію для мого салону краси.'
  },

  en: {
    // Header
    'header.services': 'Services',
    'header.benefits': 'Benefits',
    'header.pricing': 'Pricing',
    'header.testimonials': 'Testimonials',
    'header.contact': 'Contact',
    'header.consultation': 'Free Consultation',

    // Hero
    'hero.title': 'Save 3 hours daily in your beauty salon',
    'hero.subtitle': 'Automation that pays for itself in 1 week',
    'hero.description': 'Automatic bookings, SMS reminders and client management. Salon owners save 15+ hours weekly and increase profits by 30%.',
    'hero.cta': 'Get free installation',
    'hero.demo': 'See how it works',
    'hero.integrates': 'Integrates with:',

    // Problems
    'problems.title': 'Do you recognize these',
    'problems.subtitle': 'problems?',
    'problems.description': 'Beauty salon owners in Poland spend an average of 2-3 hours daily on routine tasks that can be automated.',
    'problems.phone.title': '2-3 hours daily on phone calls',
    'problems.phone.description': 'Constant phone calls interrupt client work and reduce service quality. One call every 15 minutes all day long.',
    'problems.noshow.title': '30% of clients don\'t show up',
    'problems.noshow.description': 'Without reminders, 30% of clients forget their appointment. One lost client means 200+ PLN monthly loss.',
    'problems.schedule.title': 'Chaos in schedules',
    'problems.schedule.description': 'Double bookings, time mistakes, lost notes. Schedule chaos costs 500+ PLN weekly.',
    'problems.clients.title': 'No regular client database',
    'problems.clients.description': 'Without a client tracking system, you lose the opportunity to build loyalty and increase customer lifetime value.',
    'problems.recognize': 'Recognize these problems?',
    'problems.solution': 'We have a solution that will save you 15+ hours weekly and increase profits by 30%.',
    'problems.see_solution': 'See the solution',

    // Solutions
    'solutions.title': 'How automation',
    'solutions.subtitle': 'solves problems',
    'solutions.description': '5 key automations that transform your salon into a modern business operating 24/7.',
    'solutions.booking.title': 'Automatic online bookings',
    'solutions.booking.process': 'Clients book through Instagram, WhatsApp or website. System automatically confirms and adds to calendar.',
    'solutions.booking.result': '90% fewer calls, 24/7 availability',
    'solutions.reminders.title': 'Smart reminders',
    'solutions.reminders.process': 'Automatic SMS/WhatsApp 24h and 2h before appointment. Client confirms with one click.',
    'solutions.reminders.result': '70% fewer no-shows, 2h daily savings',
    'solutions.database.title': 'Client database and history',
    'solutions.database.process': 'Automatic saving of data, preferences, visit history and expenses of each client.',
    'solutions.database.result': '40% more regular clients',
    'solutions.reviews.title': 'Automatic reviews',
    'solutions.reviews.process': 'After visit, client automatically receives review request for Google/Facebook.',
    'solutions.reviews.result': '300% more positive reviews',
    'solutions.analytics.title': 'Reports and analytics',
    'solutions.analytics.process': 'Automatic sales reports, popular services, profitability analysis.',
    'solutions.analytics.result': 'Better business decisions, +30% profit',
    'solutions.cta': 'See how it works',

    // How it works
    'how.title': 'How does it',
    'how.subtitle': 'work?',
    'how.description': 'Simple 5-step process. From consultation to full automation in 24 hours.',
    'how.consultation.title': 'Free analysis',
    'how.consultation.description': 'We analyze your processes and show savings potential.',
    'how.consultation.details': '30 minutes by phone or in person',
    'how.setup.title': 'Installation and setup',
    'how.setup.description': 'We install and configure all automations for your salon.',
    'how.setup.details': '2-4 hours, we do everything for you',
    'how.save.title': 'Training and support',
    'how.save.description': 'We show you how to use the system and support you for the first month.',
    'how.save.details': '30 minutes training + 30 days support',
    'how.start.title': 'Ready for automation?',
    'how.start.description': 'Book a free consultation and see how much you can save.',
    'how.start.cta': 'Book free consultation',

    // Results
    'results.title': 'Results of our',
    'results.subtitle': 'clients',
    'results.description': 'Concrete results from salons already using automation.',
    'results.noshow': 'fewer no-shows',
    'results.noshow.description': 'Automatic reminders reduce no-shows from 30% to 5%',
    'results.time': 'hours saved',
    'results.time.description': 'Daily more time for clients and salon development',
    'results.bookings': 'more bookings',
    'results.bookings.description': '24/7 availability increases bookings by 30%',
    'results.profit': 'more profit',
    'results.profit.description': 'Monthly thanks to better organization and more clients',
    'results.roi.title': 'Automation pays for itself in 1 week',
    'results.roi.description': 'Average salon saves 1800 PLN monthly on working time. Automation cost: €400 + €50/month.',
    'results.roi.cta': 'Calculate your savings',

    // Calculator
    'calculator.title': 'Calculate your',
    'calculator.subtitle': 'savings',
    'calculator.description': 'Find out how much time and money you\'ll save with automation in your salon.',
    'calculator.params': 'Your salon parameters',
    'calculator.appointments': 'Daily appointments:',
    'calculator.time': 'Minutes per appointment (phone + notes):',
    'calculator.rate': 'Your hourly rate:',
    'calculator.savings': 'Your savings',
    'calculator.daily': 'daily',
    'calculator.monthly': 'monthly',
    'calculator.payback': 'ROI in',
    'calculator.payback.week': 'week',
    'calculator.payback.weeks': 'weeks',
    'calculator.payback.then': 'Then pure savings!',
    'calculator.cta': 'Start saving',
    'min': 'min',
    'monthly': 'monthly',

    // Pricing
    'pricing.title': 'One price,',
    'pricing.subtitle': 'everything',
    'pricing.all_included': 'included',
    'pricing.description': 'Transparent pricing without hidden costs. Compare with competitors and see the difference.',
    'pricing.special': 'INTRODUCTORY OFFER',
    'pricing.standard': 'Standard price',
    'pricing.setup': 'setup',
    'pricing.monthly': 'Monthly support and updates',
    'pricing.includes': 'What you get',
    'pricing.feature1': 'Automatic bookings from Instagram/WhatsApp/website',
    'pricing.feature2': 'Smart SMS/WhatsApp reminders',
    'pricing.feature3': 'Client database with visit history',
    'pricing.feature4': 'Automatic review requests',
    'pricing.feature5': 'Sales reports and analytics',
    'pricing.feature6': 'Integration with popular calendars',
    'pricing.feature7': '24/7 technical support',
    'pricing.bonuses': 'Bonuses for first 50 salons',
    'pricing.bonus1': 'Free installation (value €200)',
    'pricing.bonus2': 'Free team training (value €150)',
    'pricing.bonus3': 'First month support free',
    'pricing.cta': 'Reserve your automation',
    'pricing.guarantee1': '30-day guarantee',
    'pricing.guarantee1.desc': 'Not satisfied? Money back',
    'pricing.guarantee2': '24h installation',
    'pricing.guarantee2.desc': 'Quick implementation without downtime',
    'pricing.guarantee3': 'Free support',
    'pricing.guarantee3.desc': 'First month technical support free',

    // Testimonials
    'testimonials.title': 'What salon owners',
    'testimonials.subtitle': 'say',
    'testimonials.description': 'Real reviews from salons already using automation.',
    'testimonials.1.name': 'Anna Kowalska',
    'testimonials.1.salon': 'Salon Anna, Krakow',
    'testimonials.1.text': 'In the first month, no-shows dropped from 30% to 5%. I save 3 hours daily that I can now dedicate to clients. Automation paid for itself in a week!',
    'testimonials.2.name': 'Marta Nowak',
    'testimonials.2.salon': 'Beauty Studio, Wroclaw',
    'testimonials.2.text': 'Clients love booking through Instagram. I have 40% more regular clients and can finally focus on what I love - working with clients.',
    'testimonials.3.name': 'Katarzyna Wisniewska',
    'testimonials.3.salon': 'Glow Salon, Warsaw',
    'testimonials.3.text': 'Automatic reminders are a game changer. I earn 500 PLN more monthly just because clients don\'t forget appointments.',
    'testimonials.integrations': 'Integrates with popular platforms',
    'testimonials.others': 'And many others...',

    // FAQ
    'faq.title': 'Frequently asked',
    'faq.subtitle': 'questions',
    'faq.description': 'Answers to the most common questions about beauty salon automation.',
    'faq.1.question': 'Isn\'t €400 + €50/month too expensive?',
    'faq.1.answer': 'It costs less than 2 haircuts but saves 60 hours monthly. Average salon recovers investment in first week thanks to time savings and fewer no-shows.',
    'faq.2.question': 'Isn\'t it too complicated?',
    'faq.2.answer': 'Not at all! Setup takes 24 hours and we do everything for you. Usage is as simple as WhatsApp. Plus you get free training.',
    'faq.3.question': 'What if I can\'t use it?',
    'faq.3.answer': 'We provide free training for you and your team plus 30 days of full technical support. We\'re available 24/7.',
    'faq.4.question': 'Does it work with my current system?',
    'faq.4.answer': 'Yes! We integrate with popular calendars (Google, Outlook), booking platforms (Booksy, Fresha) and social media.',
    'faq.5.question': 'What if I\'m not satisfied?',
    'faq.5.answer': 'We offer a 30-day money-back guarantee. If you\'re not satisfied with results, we refund the full amount.',
    'faq.6.question': 'How quickly will I see results?',
    'faq.6.answer': 'First results are visible after 24 hours of installation. Full benefits (fewer no-shows, more time) you\'ll feel within the first week.',
    'faq.more.title': 'Have more questions?',
    'faq.more.description': 'Contact us - we\'ll answer all your doubts.',
    'faq.call': 'Call now',
    'faq.whatsapp': 'Write on WhatsApp',

    // Contact
    'contact.title': 'Book a free',
    'contact.subtitle': 'consultation',
    'contact.description': 'We\'ll check your salon and show exactly how much you can save. Consultation lasts 30 minutes and is completely free.',
    'contact.name': 'Name',
    'contact.name.placeholder': 'Your name',
    'contact.phone': 'Phone',
    'contact.phone.placeholder': '+48 123 456 789',
    'contact.salon': 'Salon name',
    'contact.salon.placeholder': 'Your salon name',
    'contact.city': 'City',
    'contact.city.placeholder': 'Warsaw',
    'contact.comment': 'Additional information',
    'contact.comment.placeholder': 'Describe your salon, how many clients daily...',
    'contact.submit': 'Book free consultation',
    'contact.guarantees': 'Our guarantees',
    'contact.guarantee1': '100% free consultation',
    'contact.guarantee2': 'We call back in 15 minutes',
    'contact.guarantee3': 'No obligations',
    'contact.callback': 'We call back in 15 minutes',
    'contact.callback.desc': 'Our expert will contact you within 15 minutes and schedule a convenient consultation time.',
    'contact.questions': 'Have urgent questions?',
    'contact.hours': 'Mon-Fri 9:00-18:00, Sat 10:00-14:00',
    'contact.success.bonus': 'Bonus: Get a free salon audit (value €100)!',

    // Footer
    'footer.description': 'Process automation for beauty salons. Save time, increase profits.',
    'footer.links': 'Quick links',
    'footer.contact': 'Contact',
    'footer.hours': 'Working hours',
    'footer.hours.weekdays': 'Mon-Fri: 9:00-18:00',
    'footer.hours.saturday': 'Saturday: 10:00-14:00',
    'footer.hours.sunday': 'Sunday: Closed',
    'footer.consultation': 'Free consultation available!',
    'footer.copyright': '© 2025 Beauty Automation. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // WhatsApp
    'whatsapp.message': 'Hi! I would like to learn more about automation for my beauty salon.'
  }
};

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

export const LanguageProvider: React.FC<{ children: ReactNode }> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pl');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = () => {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};