import React, { createContext, useContext, useState, ReactNode } from 'react';

export type Language = 'pl' | 'ru' | 'uk' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations = {
  pl: {
    // Header
    'header.services': 'Usługi',
    'header.benefits': 'Korzyści',
    'header.pricing': 'Cennik',
    'header.testimonials': 'Opinie',
    'header.contact': 'Kontakt',
    'header.consultation': 'Bezpłatna konsultacja',

    // Hero
    'hero.title': 'Automatyzacja dla Salonów Piękności',
    'hero.subtitle': 'Oszczędzaj 3 godziny dziennie!',
    'hero.description': 'Automatyczne zapisywanie, przypomnienia i baza klientów. Więcej czasu na klientów, mniej administracji.',
    'hero.cta': 'Otrzymaj bezpłatną konfigurację',
    'hero.demo': 'Zobacz demo (2 min)',
    'hero.integrates': 'Integruje się z:',

    // Problems
    'problems.title': 'Rozpoznajesz siebie?',
    'problems.subtitle': 'Zmęczyłaś się traceniem czasu na administrację?',
    'problems.description': 'Większość właścicieli salonów piękności zmaga się z tymi samymi problemami każdego dnia',
    'problems.phone.title': '2-3 godziny dziennie na telefony i zapisywanie',
    'problems.phone.description': 'Zamiast pracować z klientami, tracisz czas na niekończące się rozmowy o potwierdzeniu wizyt',
    'problems.noshow.title': '30% klientów nie przychodzi bez przypomnienia',
    'problems.noshow.description': 'Strata zysku przez no-show klientów, którzy po prostu zapomnieli o wizycie',
    'problems.schedule.title': 'Zamieszanie w harmonogramie',
    'problems.schedule.description': 'Podwójne rezerwacje, konflikty w harmonogramie, niezadowoleni klienci',
    'problems.clients.title': 'Tracisz klientów przez wolną obsługę',
    'problems.clients.description': 'Klienci odchodzą do konkurencji, która odpowiada szybciej',
    'problems.recognize': 'Czy to brzmi znajomo?',
    'problems.solution': 'Jeśli tak, to mamy dla Ciebie rozwiązanie, które automatyzuje wszystkie te procesy i pozwala Ci skupić się na tym, co najważniejsze - na klientach.',
    'problems.see_solution': 'Zobacz rozwiązanie',

    // Solutions
    'solutions.title': 'Automatyzujemy wszystkie rutynowe procesy',
    'solutions.subtitle': 'w ciągu 1 dnia',
    'solutions.description': '5 kluczowych automatyzacji, które uratują Twój czas i zwiększą zyski',
    'solutions.booking.title': 'Automatyczne zapisywanie',
    'solutions.booking.process': 'Instagram/Facebook → Autopotwierdzenie → Kalendarz',
    'solutions.booking.result': 'Zapisy 24/7 bez Twojego udziału',
    'solutions.reminders.title': 'Inteligentne przypomnienia',
    'solutions.reminders.process': 'Dzień przed wizytą → SMS/WhatsApp → Potwierdzenie',
    'solutions.reminders.result': '70% redukcja no-show',
    'solutions.database.title': 'Baza klientów',
    'solutions.database.process': 'Autozapisywanie danych → Historia zabiegów → Spersonalizowane oferty',
    'solutions.database.result': '40% więcej powtórnych wizyt',
    'solutions.reviews.title': 'Automatyczne opinie',
    'solutions.reviews.process': 'Po wizycie → Prośba o opinię → Publikacja w Google/Facebook',
    'solutions.reviews.result': '3x więcej pozytywnych opinii',
    'solutions.analytics.title': 'Analityka zysku',
    'solutions.analytics.process': 'Autoraporty → Analiza usług → Rekomendacje cenowe',
    'solutions.analytics.result': 'Wzrost zysku o 25%',
    'solutions.cta': 'Zobacz, jak to działa',

    // How it works
    'how.title': 'Jak uruchomić automatyzację',
    'how.subtitle': 'w Twoim salonie',
    'how.description': '3 proste kroki do pełnej automatyzacji',
    'how.consultation.title': 'Bezpłatna konsultacja',
    'how.consultation.description': 'Analizujemy Twoje procesy w 30 minut',
    'how.consultation.details': 'Pokazujemy możliwości automatyzacji',
    'how.setup.title': 'Konfiguracja w 1 dzień',
    'how.setup.description': 'Integrujemy z Instagram, WhatsApp, Twoim kalendarzem',
    'how.setup.details': 'Szkolimy administratora',
    'how.save.title': 'Oszczędzaj czas i pieniądze',
    'how.save.description': 'Otrzymujesz 3+ godziny wolnego czasu dziennie',
    'how.save.details': 'Zwiększasz zysk o €500+ miesięcznie',
    'how.start.title': 'Rozpocznij już dziś!',
    'how.start.description': 'Pierwsza automatyzacja jest całkowicie bezpłatna',
    'how.start.cta': 'Zacznij bezpłatnie',

    // Results
    'results.title': 'Rezultaty naszych klientów',
    'results.subtitle': 'w pierwszym miesiącu',
    'results.description': 'Prawdziwe wyniki z prawdziwych salonów piękności',
    'results.noshow': 'mniej no-show',
    'results.noshow.description': 'Dzięki automatycznym przypomnieniom',
    'results.time': 'godziny oszczędności dziennie',
    'results.time.description': 'Więcej czasu na pracę z klientami',
    'results.bookings': 'więcej zapisów',
    'results.bookings.description': 'Automatyczny odbiór zgłoszeń 24/7',
    'results.profit': 'dodatkowego zysku',
    'results.profit.description': 'Dzięki wzrostowi powtórnych wizyt',
    'results.roi.title': 'Średni zwrot z inwestycji: 400% w pierwszym miesiącu',
    'results.roi.description': 'Nasze automatyzacje się opłacają już po 3 tygodniach',
    'results.roi.cta': 'Oblicz swoje oszczędności',

    // Calculator
    'calculator.title': 'Oblicz oszczędności',
    'calculator.subtitle': 'dla Twojego salonu',
    'calculator.description': 'Interaktywny kalkulator pokazuje, ile czasu i pieniędzy możesz zaoszczędzić',
    'calculator.params': 'Parametry Twojego salonu',
    'calculator.appointments': 'Liczba zapisów dziennie:',
    'calculator.time': 'Czas na obsługę jednego zapisu:',
    'calculator.rate': 'Twoja stawka za godzinę:',
    'calculator.savings': 'Twoje oszczędności',
    'calculator.daily': 'oszczędności dziennie',
    'calculator.monthly': 'oszczędności miesięcznie',
    'calculator.payback': 'Automatyzacja zwróci się w',
    'calculator.payback.weeks': 'tygodnie',
    'calculator.payback.week': 'tydzień',
    'calculator.payback.then': 'Potem to są czyste oszczędności',
    'calculator.cta': 'Chcę zaoszczędzić',

    // Pricing
    'pricing.title': 'Pakiet',
    'pricing.subtitle': "'Automatyzacja Piękności'",
    'pricing.all_included': '- Wszystko włączone',
    'pricing.description': 'Kompletne rozwiązanie automatyzacji dla Twojego salonu',
    'pricing.special': 'OFERTA SPECJALNA',
    'pricing.standard': 'Standardowa cena',
    'pricing.setup': 'konfiguracja jednorazowa',
    'pricing.monthly': 'ciągłe wsparcie',
    'pricing.save': 'Oszczędzasz 60%',
    'pricing.includes': 'Co otrzymujesz:',
    'pricing.feature1': 'Automatyzacja zapisu z mediów społecznościowych',
    'pricing.feature2': 'SMS i WhatsApp przypomnienia',
    'pricing.feature3': 'Baza klientów z historią',
    'pricing.feature4': 'Automatyczne opinie',
    'pricing.feature5': 'Analityka i raporty',
    'pricing.feature6': 'Szkolenie administratora',
    'pricing.feature7': 'Wsparcie techniczne w WhatsApp',
    'pricing.bonuses': 'Bonusy:',
    'pricing.bonus1': 'Pierwsza konfiguracja BEZPŁATNIE (oszczędność €200)',
    'pricing.bonus2': 'Pierwszy miesiąc wsparcia w prezencie',
    'pricing.bonus3': 'Osobisty menedżer na miesiąc',
    'pricing.cta': 'Otrzymaj bezpłatną konfigurację teraz',
    'pricing.guarantee1': 'Bez przedpłaty',
    'pricing.guarantee1.desc': 'Płacisz dopiero po uruchomieniu',
    'pricing.guarantee2': 'Wynik w 24 godziny',
    'pricing.guarantee2.desc': 'Szybka konfiguracja i efekty',
    'pricing.guarantee3': 'Nie pasuje - wyłączamy za darmo',
    'pricing.guarantee3.desc': 'Gwarancja satysfakcji',

    // Testimonials
    'testimonials.title': 'Co mówią właściciele salonów',
    'testimonials.subtitle': 'o naszej automatyzacji',
    'testimonials.description': 'Prawdziwe opinie od prawdziwych klientów',
    'testimonials.1.name': 'Anna Kowalska',
    'testimonials.1.salon': 'Salon Bella',
    'testimonials.1.text': 'W ciągu miesiąca zaoszczędziłam 90 godzin na administrowaniu. Teraz mogę przyjąć o 40% więcej klientów!',
    'testimonials.2.name': 'Tomasz Nowak',
    'testimonials.2.salon': 'Beauty Studio',
    'testimonials.2.text': 'No-show spadły z 30% do 8%. Automatyzacja zwróciła się w 3 tygodnie!',
    'testimonials.3.name': 'Katarzyna Zielińska',
    'testimonials.3.salon': 'Glow Salon',
    'testimonials.3.text': 'Klienci uwielbiają przypomnienia WhatsApp. Ocena w Google wzrosła z 4.2 do 4.8!',
    'testimonials.integrations': 'Integrujemy się z najpopularniejszymi platformami',
    'testimonials.others': 'I wiele innych platform, z którymi już pracujesz',

    // Contact
    'contact.title': 'Otrzymaj bezpłatną konfigurację',
    'contact.subtitle': 'pierwszej automatyzacji',
    'contact.description': 'Zostaw zgłoszenie, a skonfigurujemy automatyczne przypomnienia dla Twojego salonu całkowicie bezpłatnie',
    'contact.name': 'Twoje imię *',
    'contact.name.placeholder': 'Wpisz swoje imię',
    'contact.phone': 'Telefon *',
    'contact.phone.placeholder': '+48 123 456 789',
    'contact.salon': 'Nazwa salonu *',
    'contact.salon.placeholder': 'Nazwa Twojego salonu',
    'contact.city': 'Miasto *',
    'contact.city.placeholder': 'Wpisz swoje miasto',
    'contact.comment': 'Dodatkowe informacje',
    'contact.comment.placeholder': 'Opisz swoje potrzeby lub zadaj pytanie...',
    'contact.submit': 'Otrzymaj bezpłatną automatyzację',
    'contact.guarantees': 'Gwarancje pod formularzem:',
    'contact.guarantee1': 'Żadnej przedpłaty',
    'contact.guarantee2': 'Wynik w 24 godziny',
    'contact.guarantee3': 'Nie pasuje - wyłączamy za darmo',
    'contact.callback': 'Skontaktujemy się w ciągu 2 godzin!',
    'contact.callback.desc': 'Nasz ekspert zadzwoni do Ciebie, aby omówić Twoje potrzeby i zaplanować bezpłatną konfigurację pierwszej automatyzacji.',
    'contact.questions': 'Masz pytania? Zadzwoń od razu:',
    'contact.hours': 'Pon-Pt: 9:00 - 18:00 | Sob: 10:00 - 15:00',
    'contact.success.title': 'Dziękujemy za zgłoszenie!',
    'contact.success.description': 'Skontaktujemy się z Tobą w ciągu 2 godzin, aby umówić bezpłatną konsultację.',
    'contact.success.bonus': 'Pierwsza automatyzacja będzie skonfigurowana całkowicie bezpłatnie!',

    // FAQ
    'faq.title': 'Najczęściej zadawane',
    'faq.subtitle': 'pytania',
    'faq.description': 'Odpowiedzi na najważniejsze pytania dotyczące automatyzacji',
    'faq.1.question': 'Czy moje dane są bezpieczne?',
    'faq.1.answer': 'Tak, używamy europejskich standardów GDPR. Wszystkie dane są szyfrowane i przechowywane na bezpiecznych serwerach w Europie. Nigdy nie udostępniamy danych osobowych klientów osobom trzecim.',
    'faq.2.question': 'Ile czasu zajmuje konfiguracja?',
    'faq.2.answer': 'Podstawowa automatyzacja jest konfigurowana w ciągu 2-4 godzin. Większość procesów działa już pierwszego dnia. Pełna konfiguracja wszystkich automatyzacji zajmuje maksymalnie 1 dzień roboczy.',
    'faq.3.question': 'Co jeśli automatyzacja mi nie będzie odpowiadać?',
    'faq.3.answer': 'Pierwszy miesiąc pracy jest bezpłatny. Jeśli nie będziesz zadowolona z rezultatów, wyłączymy wszystkie automatyzacje bezpłatnie. Nie ma żadnych zobowiązań ani kar umownych.',
    'faq.4.question': 'Czy muszę zmieniać system zapisów?',
    'faq.4.answer': 'Nie, integrujemy się z każdym istniejącym systemem. Współpracujemy z Booksy, Fresha, Planity i wieloma innymi. Możesz też dalej korzystać z tradycyjnego kalendarza.',
    'faq.5.question': 'Czy automatyzacja jest skomplikowana w obsłudze?',
    'faq.5.answer': 'Nie, wszystko działa automatycznie. Szkolenie administratora trwa tylko 30 minut. System jest intuicyjny i nie wymaga dodatkowej wiedzy technicznej.',
    'faq.6.question': 'Co wchodzi w skład miesięcznego wsparcia?',
    'faq.6.answer': 'Wsparcie techniczne przez WhatsApp, regularne aktualizacje systemu, konsultacje w sprawie optymalizacji procesów, dodawanie nowych automatyzacji i bezpłatne rozwiązywanie problemów.',
    'faq.more.title': 'Masz inne pytania?',
    'faq.more.description': 'Skontaktuj się z nami bezpośrednio - odpowiemy w ciągu 30 minut',
    'faq.call': 'Zadzwoń: +48 123 456 789',
    'faq.whatsapp': 'Napisz na WhatsApp',

    // Footer
    'footer.description': 'Automatyzacja procesów dla salonów piękności. Oszczędzamy Twój czas i zwiększamy zyski.',
    'footer.links': 'Szybkie linki',
    'footer.contact': 'Kontakt',
    'footer.hours': 'Godziny pracy',
    'footer.hours.weekdays': 'Pon-Pt: 9:00 - 18:00',
    'footer.hours.saturday': 'Sobota: 10:00 - 15:00',
    'footer.hours.sunday': 'Niedziela: Zamknięte',
    'footer.consultation': 'Bezpłatna konsultacja w 24h!',
    'footer.copyright': '© 2025 Beauty Automation. Wszelkie prawa zastrzeżone.',
    'footer.privacy': 'Polityka prywatności',
    'footer.terms': 'Regulamin',

    // WhatsApp
    'whatsapp.message': 'Cześć! Chciałbym dowiedzieć się więcej o automatyzacji dla mojego salonu piękności.',

    // Common
    'min': 'min',
    'monthly': 'miesięcznie',
  },
  
  ru: {
    // Header
    'header.services': 'Услуги',
    'header.benefits': 'Преимущества',
    'header.pricing': 'Цены',
    'header.testimonials': 'Отзывы',
    'header.contact': 'Контакты',
    'header.consultation': 'Бесплатная консультация',

    // Hero
    'hero.title': 'Автоматизация для Салонов Красоты',
    'hero.subtitle': 'Экономьте 3 часа в день!',
    'hero.description': 'Автоматическая запись, напоминания и база клиентов. Больше времени для клиентов, меньше администрации.',
    'hero.cta': 'Получить бесплатную настройку',
    'hero.demo': 'Посмотреть демо (2 мин)',
    'hero.integrates': 'Интегрируется с:',

    // Problems
    'problems.title': 'Узнали себя?',
    'problems.subtitle': 'Устали тратить время на администрацию?',
    'problems.description': 'Большинство владельцев салонов красоты сталкиваются с одними и теми же проблемами каждый день',
    'problems.phone.title': '2-3 часа в день на звонки и запись',
    'problems.phone.description': 'Вместо работы с клиентами тратите время на бесконечные звонки для подтверждения визитов',
    'problems.noshow.title': '30% клиентов не приходят без напоминания',
    'problems.noshow.description': 'Потеря прибыли из-за no-show клиентов, которые просто забыли о визите',
    'problems.schedule.title': 'Путаница в расписании',
    'problems.schedule.description': 'Двойные записи, конфликты в расписании, недовольные клиенты',
    'problems.clients.title': 'Теряете клиентов из-за медленного сервиса',
    'problems.clients.description': 'Клиенты уходят к конкурентам, которые отвечают быстрее',
    'problems.recognize': 'Это звучит знакомо?',
    'problems.solution': 'Если да, то у нас есть для вас решение, которое автоматизирует все эти процессы и позволяет сосредоточиться на самом важном - на клиентах.',
    'problems.see_solution': 'Посмотреть решение',

    // Solutions
    'solutions.title': 'Автоматизируем все рутинные процессы',
    'solutions.subtitle': 'за 1 день',
    'solutions.description': '5 ключевых автоматизаций, которые сэкономят ваше время и увеличат прибыль',
    'solutions.booking.title': 'Автоматическая запись',
    'solutions.booking.process': 'Instagram/Facebook → Автоподтверждение → Календарь',
    'solutions.booking.result': 'Записи 24/7 без вашего участия',
    'solutions.reminders.title': 'Умные напоминания',
    'solutions.reminders.process': 'За день до визита → SMS/WhatsApp → Подтверждение',
    'solutions.reminders.result': '70% сокращение no-show',
    'solutions.database.title': 'База клиентов',
    'solutions.database.process': 'Автосохранение данных → История процедур → Персональные предложения',
    'solutions.database.result': '40% больше повторных визитов',
    'solutions.reviews.title': 'Автоматические отзывы',
    'solutions.reviews.process': 'После визита → Просьба об отзыве → Публикация в Google/Facebook',
    'solutions.reviews.result': 'В 3 раза больше положительных отзывов',
    'solutions.analytics.title': 'Аналитика прибыли',
    'solutions.analytics.process': 'Автоотчеты → Анализ услуг → Рекомендации по ценам',
    'solutions.analytics.result': 'Увеличение прибыли на 25%',
    'solutions.cta': 'Посмотреть, как это работает',

    // How it works
    'how.title': 'Как запустить автоматизацию',
    'how.subtitle': 'в вашем салоне',
    'how.description': '3 простых шага к полной автоматизации',
    'how.consultation.title': 'Бесплатная консультация',
    'how.consultation.description': 'Анализируем ваши процессы за 30 минут',
    'how.consultation.details': 'Показываем возможности автоматизации',
    'how.setup.title': 'Настройка за 1 день',
    'how.setup.description': 'Интегрируем с Instagram, WhatsApp, вашим календарем',
    'how.setup.details': 'Обучаем администратора',
    'how.save.title': 'Экономьте время и деньги',
    'how.save.description': 'Получаете 3+ часа свободного времени ежедневно',
    'how.save.details': 'Увеличиваете прибыль на €500+ в месяц',
    'how.start.title': 'Начните уже сегодня!',
    'how.start.description': 'Первая автоматизация полностью бесплатна',
    'how.start.cta': 'Начать бесплатно',

    // Results
    'results.title': 'Результаты наших клиентов',
    'results.subtitle': 'в первый месяц',
    'results.description': 'Реальные результаты из реальных салонов красоты',
    'results.noshow': 'меньше no-show',
    'results.noshow.description': 'Благодаря автоматическим напоминаниям',
    'results.time': 'часа экономии ежедневно',
    'results.time.description': 'Больше времени для работы с клиентами',
    'results.bookings': 'больше записей',
    'results.bookings.description': 'Автоматический прием заявок 24/7',
    'results.profit': 'дополнительной прибыли',
    'results.profit.description': 'За счет роста повторных визитов',
    'results.roi.title': 'Средняя окупаемость: 400% в первый месяц',
    'results.roi.description': 'Наши автоматизации окупаются уже через 3 недели',
    'results.roi.cta': 'Рассчитать свою экономию',

    // Calculator
    'calculator.title': 'Рассчитайте экономию',
    'calculator.subtitle': 'для вашего салона',
    'calculator.description': 'Интерактивный калькулятор показывает, сколько времени и денег вы можете сэкономить',
    'calculator.params': 'Параметры вашего салона',
    'calculator.appointments': 'Количество записей в день:',
    'calculator.time': 'Время на обработку одной записи:',
    'calculator.rate': 'Ваша ставка в час:',
    'calculator.savings': 'Ваша экономия',
    'calculator.daily': 'экономии ежедневно',
    'calculator.monthly': 'экономии в месяц',
    'calculator.payback': 'Автоматизация окупится за',
    'calculator.payback.weeks': 'недели',
    'calculator.payback.week': 'неделю',
    'calculator.payback.then': 'Потом это чистая экономия',
    'calculator.cta': 'Хочу сэкономить',

    // Pricing
    'pricing.title': 'Пакет',
    'pricing.subtitle': "'Автоматизация Красоты'",
    'pricing.all_included': '- Все включено',
    'pricing.description': 'Комплексное решение автоматизации для вашего салона',
    'pricing.special': 'СПЕЦИАЛЬНОЕ ПРЕДЛОЖЕНИЕ',
    'pricing.standard': 'Стандартная цена',
    'pricing.setup': 'разовая настройка',
    'pricing.monthly': 'постоянная поддержка',
    'pricing.save': 'Экономите 60%',
    'pricing.includes': 'Что вы получаете:',
    'pricing.feature1': 'Автоматизация записи из социальных сетей',
    'pricing.feature2': 'SMS и WhatsApp напоминания',
    'pricing.feature3': 'База клиентов с историей',
    'pricing.feature4': 'Автоматические отзывы',
    'pricing.feature5': 'Аналитика и отчеты',
    'pricing.feature6': 'Обучение администратора',
    'pricing.feature7': 'Техподдержка в WhatsApp',
    'pricing.bonuses': 'Бонусы:',
    'pricing.bonus1': 'Первая настройка БЕСПЛАТНО (экономия €200)',
    'pricing.bonus2': 'Первый месяц поддержки в подарок',
    'pricing.bonus3': 'Персональный менеджер на месяц',
    'pricing.cta': 'Получить бесплатную настройку сейчас',
    'pricing.guarantee1': 'Без предоплаты',
    'pricing.guarantee1.desc': 'Платите только после запуска',
    'pricing.guarantee2': 'Результат за 24 часа',
    'pricing.guarantee2.desc': 'Быстрая настройка и эффекты',
    'pricing.guarantee3': 'Не подходит - отключаем бесплатно',
    'pricing.guarantee3.desc': 'Гарантия удовлетворения',

    // Testimonials
    'testimonials.title': 'Что говорят владельцы салонов',
    'testimonials.subtitle': 'о нашей автоматизации',
    'testimonials.description': 'Реальные отзывы от реальных клиентов',
    'testimonials.1.name': 'Анна Ковальская',
    'testimonials.1.salon': 'Салон Белла',
    'testimonials.1.text': 'За месяц сэкономила 90 часов на администрировании. Теперь могу принять на 40% больше клиентов!',
    'testimonials.2.name': 'Томаш Новак',
    'testimonials.2.salon': 'Beauty Studio',
    'testimonials.2.text': 'No-show снизились с 30% до 8%. Автоматизация окупилась за 3 недели!',
    'testimonials.3.name': 'Катажина Зелинская',
    'testimonials.3.salon': 'Glow Salon',
    'testimonials.3.text': 'Клиенты обожают напоминания в WhatsApp. Рейтинг в Google вырос с 4.2 до 4.8!',
    'testimonials.integrations': 'Интегрируемся с самыми популярными платформами',
    'testimonials.others': 'И многие другие платформы, с которыми вы уже работаете',

    // Contact
    'contact.title': 'Получите бесплатную настройку',
    'contact.subtitle': 'первой автоматизации',
    'contact.description': 'Оставьте заявку, и мы настроим автоматические напоминания для вашего салона совершенно бесплатно',
    'contact.name': 'Ваше имя *',
    'contact.name.placeholder': 'Введите ваше имя',
    'contact.phone': 'Телефон *',
    'contact.phone.placeholder': '+7 123 456 789',
    'contact.salon': 'Название салона *',
    'contact.salon.placeholder': 'Название вашего салона',
    'contact.city': 'Город *',
    'contact.city.placeholder': 'Введите ваш город',
    'contact.comment': 'Дополнительная информация',
    'contact.comment.placeholder': 'Опишите ваши потребности или задайте вопрос...',
    'contact.submit': 'Получить бесплатную автоматизацию',
    'contact.guarantees': 'Гарантии под формой:',
    'contact.guarantee1': 'Никакой предоплаты',
    'contact.guarantee2': 'Результат за 24 часа',
    'contact.guarantee3': 'Не подходит - отключаем бесплатно',
    'contact.callback': 'Свяжемся в течение 2 часов!',
    'contact.callback.desc': 'Наш эксперт позвонит вам, чтобы обсудить ваши потребности и запланировать бесплатную настройку первой автоматизации.',
    'contact.questions': 'Есть вопросы? Звоните прямо сейчас:',
    'contact.hours': 'Пн-Пт: 9:00 - 18:00 | Сб: 10:00 - 15:00',
    'contact.success.title': 'Спасибо за заявку!',
    'contact.success.description': 'Мы свяжемся с вами в течение 2 часов, чтобы назначить бесплатную консультацию.',
    'contact.success.bonus': 'Первая автоматизация будет настроена совершенно бесплатно!',

    // FAQ
    'faq.title': 'Часто задаваемые',
    'faq.subtitle': 'вопросы',
    'faq.description': 'Ответы на самые важные вопросы об автоматизации',
    'faq.1.question': 'Безопасны ли мои данные?',
    'faq.1.answer': 'Да, мы используем европейские стандарты GDPR. Все данные зашифрованы и хранятся на безопасных серверах в Европе. Мы никогда не передаем персональные данные клиентов третьим лицам.',
    'faq.2.question': 'Сколько времени займет настройка?',
    'faq.2.answer': 'Базовая автоматизация настраивается в течение 2-4 часов. Большинство процессов работают уже в первый день. Полная настройка всех автоматизаций занимает максимум 1 рабочий день.',
    'faq.3.question': 'Что если автоматизация мне не подойдет?',
    'faq.3.answer': 'Первый месяц работы бесплатный. Если вы не будете довольны результатами, мы отключим все автоматизации бесплатно. Никаких обязательств или штрафов.',
    'faq.4.question': 'Нужно ли менять систему записи?',
    'faq.4.answer': 'Нет, мы интегрируемся с любой существующей системой. Работаем с Booksy, Fresha, Planity и многими другими. Можете продолжать пользоваться традиционным календарем.',
    'faq.5.question': 'Сложна ли автоматизация в использовании?',
    'faq.5.answer': 'Нет, все работает автоматически. Обучение администратора занимает всего 30 минут. Система интуитивна и не требует дополнительных технических знаний.',
    'faq.6.question': 'Что входит в ежемесячную поддержку?',
    'faq.6.answer': 'Техническая поддержка через WhatsApp, регулярные обновления системы, консультации по оптимизации процессов, добавление новых автоматизаций и бесплатное решение проблем.',
    'faq.more.title': 'Есть другие вопросы?',
    'faq.more.description': 'Свяжитесь с нами напрямую - ответим в течение 30 минут',
    'faq.call': 'Звоните: +7 123 456 789',
    'faq.whatsapp': 'Написать в WhatsApp',

    // Footer
    'footer.description': 'Автоматизация процессов для салонов красоты. Экономим ваше время и увеличиваем прибыль.',
    'footer.links': 'Быстрые ссылки',
    'footer.contact': 'Контакты',
    'footer.hours': 'Часы работы',
    'footer.hours.weekdays': 'Пн-Пт: 9:00 - 18:00',
    'footer.hours.saturday': 'Суббота: 10:00 - 15:00',
    'footer.hours.sunday': 'Воскресенье: Закрыто',
    'footer.consultation': 'Бесплатная консультация за 24ч!',
    'footer.copyright': '© 2025 Beauty Automation. Все права защищены.',
    'footer.privacy': 'Политика конфиденциальности',
    'footer.terms': 'Условия использования',

    // WhatsApp
    'whatsapp.message': 'Привет! Хотел бы узнать больше об автоматизации для моего салона красоты.',

    // Common
    'min': 'мин',
    'monthly': 'в месяц',
  },

  uk: {
    // Header
    'header.services': 'Послуги',
    'header.benefits': 'Переваги',
    'header.pricing': 'Ціни',
    'header.testimonials': 'Відгуки',
    'header.contact': 'Контакти',
    'header.consultation': 'Безкоштовна консультація',

    // Hero
    'hero.title': 'Автоматизація для Салонів Краси',
    'hero.subtitle': 'Економте 3 години на день!',
    'hero.description': 'Автоматичний запис, нагадування та база клієнтів. Більше часу для клієнтів, менше адміністрації.',
    'hero.cta': 'Отримати безкоштовне налаштування',
    'hero.demo': 'Подивитися демо (2 хв)',
    'hero.integrates': 'Інтегрується з:',

    // Problems
    'problems.title': 'Впізнали себе?',
    'problems.subtitle': 'Втомилися витрачати час на адміністрацію?',
    'problems.description': 'Більшість власників салонів краси стикаються з однаковими проблемами щодня',
    'problems.phone.title': '2-3 години на день на дзвінки та запис',
    'problems.phone.description': 'Замість роботи з клієнтами витрачаєте час на нескінченні дзвінки для підтвердження візитів',
    'problems.noshow.title': '30% клієнтів не приходять без нагадування',
    'problems.noshow.description': 'Втрата прибутку через no-show клієнтів, які просто забули про візит',
    'problems.schedule.title': 'Плутанина в розкладі',
    'problems.schedule.description': 'Подвійні записи, конфлікти в розкладі, незадоволені клієнти',
    'problems.clients.title': 'Втрачаєте клієнтів через повільний сервіс',
    'problems.clients.description': 'Клієнти йдуть до конкурентів, які відповідають швидше',
    'problems.recognize': 'Це звучить знайомо?',
    'problems.solution': 'Якщо так, то у нас є для вас рішення, яке автоматизує всі ці процеси і дозволяє зосередитися на найважливішому - на клієнтах.',
    'problems.see_solution': 'Подивитися рішення',

    // Solutions
    'solutions.title': 'Автоматизуємо всі рутинні процеси',
    'solutions.subtitle': 'за 1 день',
    'solutions.description': '5 ключових автоматизацій, які заощадять ваш час і збільшать прибуток',
    'solutions.booking.title': 'Автоматичний запис',
    'solutions.booking.process': 'Instagram/Facebook → Автопідтвердження → Календар',
    'solutions.booking.result': 'Записи 24/7 без вашої участі',
    'solutions.reminders.title': 'Розумні нагадування',
    'solutions.reminders.process': 'За день до візиту → SMS/WhatsApp → Підтвердження',
    'solutions.reminders.result': '70% скорочення no-show',
    'solutions.database.title': 'База клієнтів',
    'solutions.database.process': 'Автозбереження даних → Історія процедур → Персональні пропозиції',
    'solutions.database.result': '40% більше повторних візитів',
    'solutions.reviews.title': 'Автоматичні відгуки',
    'solutions.reviews.process': 'Після візиту → Прохання про відгук → Публікація в Google/Facebook',
    'solutions.reviews.result': 'У 3 рази більше позитивних відгуків',
    'solutions.analytics.title': 'Аналітика прибутку',
    'solutions.analytics.process': 'Автозвіти → Аналіз послуг → Рекомендації щодо цін',
    'solutions.analytics.result': 'Збільшення прибутку на 25%',
    'solutions.cta': 'Подивитися, як це працює',

    // How it works
    'how.title': 'Як запустити автоматизацію',
    'how.subtitle': 'у вашому салоні',
    'how.description': '3 прості кроки до повної автоматизації',
    'how.consultation.title': 'Безкоштовна консультація',
    'how.consultation.description': 'Аналізуємо ваші процеси за 30 хвилин',
    'how.consultation.details': 'Показуємо можливості автоматизації',
    'how.setup.title': 'Налаштування за 1 день',
    'how.setup.description': 'Інтегруємо з Instagram, WhatsApp, вашим календарем',
    'how.setup.details': 'Навчаємо адміністратора',
    'how.save.title': 'Економте час і гроші',
    'how.save.description': 'Отримуєте 3+ години вільного часу щодня',
    'how.save.details': 'Збільшуєте прибуток на €500+ на місяць',
    'how.start.title': 'Почніть уже сьогодні!',
    'how.start.description': 'Перша автоматизація повністю безкоштовна',
    'how.start.cta': 'Почати безкоштовно',

    // Results
    'results.title': 'Результати наших клієнтів',
    'results.subtitle': 'у перший місяць',
    'results.description': 'Реальні результати з реальних салонів краси',
    'results.noshow': 'менше no-show',
    'results.noshow.description': 'Завдяки автоматичним нагадуванням',
    'results.time': 'години економії щодня',
    'results.time.description': 'Більше часу для роботи з клієнтами',
    'results.bookings': 'більше записів',
    'results.bookings.description': 'Автоматичний прийом заявок 24/7',
    'results.profit': 'додаткового прибутку',
    'results.profit.description': 'За рахунок зростання повторних візитів',
    'results.roi.title': 'Середня окупність: 400% у перший місяць',
    'results.roi.description': 'Наші автоматизації окупаються вже через 3 тижні',
    'results.roi.cta': 'Розрахувати свою економію',

    // Calculator
    'calculator.title': 'Розрахуйте економію',
    'calculator.subtitle': 'для вашого салону',
    'calculator.description': 'Інтерактивний калькулятор показує, скільки часу і грошей ви можете заощадити',
    'calculator.params': 'Параметри вашого салону',
    'calculator.appointments': 'Кількість записів на день:',
    'calculator.time': 'Час на обробку одного запису:',
    'calculator.rate': 'Ваша ставка за годину:',
    'calculator.savings': 'Ваша економія',
    'calculator.daily': 'економії щодня',
    'calculator.monthly': 'економії на місяць',
    'calculator.payback': 'Автоматизація окупиться за',
    'calculator.payback.weeks': 'тижні',
    'calculator.payback.week': 'тиждень',
    'calculator.payback.then': 'Потім це чиста економія',
    'calculator.cta': 'Хочу заощадити',

    // Pricing
    'pricing.title': 'Пакет',
    'pricing.subtitle': "'Автоматизація Краси'",
    'pricing.all_included': '- Все включено',
    'pricing.description': 'Комплексне рішення автоматизації для вашого салону',
    'pricing.special': 'СПЕЦІАЛЬНА ПРОПОЗИЦІЯ',
    'pricing.standard': 'Стандартна ціна',
    'pricing.setup': 'разове налаштування',
    'pricing.monthly': 'постійна підтримка',
    'pricing.save': 'Економите 60%',
    'pricing.includes': 'Що ви отримуєте:',
    'pricing.feature1': 'Автоматизація запису з соціальних мереж',
    'pricing.feature2': 'SMS і WhatsApp нагадування',
    'pricing.feature3': 'База клієнтів з історією',
    'pricing.feature4': 'Автоматичні відгуки',
    'pricing.feature5': 'Аналітика та звіти',
    'pricing.feature6': 'Навчання адміністратора',
    'pricing.feature7': 'Техпідтримка в WhatsApp',
    'pricing.bonuses': 'Бонуси:',
    'pricing.bonus1': 'Перше налаштування БЕЗКОШТОВНО (економія €200)',
    'pricing.bonus2': 'Перший місяць підтримки у подарунок',
    'pricing.bonus3': 'Персональний менеджер на місяць',
    'pricing.cta': 'Отримати безкоштовне налаштування зараз',
    'pricing.guarantee1': 'Без передоплати',
    'pricing.guarantee1.desc': 'Платите тільки після запуску',
    'pricing.guarantee2': 'Результат за 24 години',
    'pricing.guarantee2.desc': 'Швидке налаштування та ефекти',
    'pricing.guarantee3': 'Не підходить - відключаємо безкоштовно',
    'pricing.guarantee3.desc': 'Гарантія задоволення',

    // Testimonials
    'testimonials.title': 'Що кажуть власники салонів',
    'testimonials.subtitle': 'про нашу автоматизацію',
    'testimonials.description': 'Реальні відгуки від реальних клієнтів',
    'testimonials.1.name': 'Анна Ковальська',
    'testimonials.1.salon': 'Салон Белла',
    'testimonials.1.text': 'За місяць заощадила 90 годин на адмініструванні. Тепер можу прийняти на 40% більше клієнтів!',
    'testimonials.2.name': 'Томаш Новак',
    'testimonials.2.salon': 'Beauty Studio',
    'testimonials.2.text': 'No-show знизилися з 30% до 8%. Автоматизація окупилася за 3 тижні!',
    'testimonials.3.name': 'Катажина Зелінська',
    'testimonials.3.salon': 'Glow Salon',
    'testimonials.3.text': 'Клієнти обожнюють нагадування в WhatsApp. Рейтинг в Google виріс з 4.2 до 4.8!',
    'testimonials.integrations': 'Інтегруємося з найпопулярнішими платформами',
    'testimonials.others': 'І багато інших платформ, з якими ви вже працюєте',

    // Contact
    'contact.title': 'Отримайте безкоштовне налаштування',
    'contact.subtitle': 'першої автоматизації',
    'contact.description': 'Залиште заявку, і ми налаштуємо автоматичні нагадування для вашого салону абсолютно безкоштовно',
    'contact.name': 'Ваше ім\'я *',
    'contact.name.placeholder': 'Введіть ваше ім\'я',
    'contact.phone': 'Телефон *',
    'contact.phone.placeholder': '+380 123 456 789',
    'contact.salon': 'Назва салону *',
    'contact.salon.placeholder': 'Назва вашого салону',
    'contact.city': 'Місто *',
    'contact.city.placeholder': 'Введіть ваше місто',
    'contact.comment': 'Додаткова інформація',
    'contact.comment.placeholder': 'Опишіть ваші потреби або поставте питання...',
    'contact.submit': 'Отримати безкоштовну автоматизацію',
    'contact.guarantees': 'Гарантії під формою:',
    'contact.guarantee1': 'Жодної передоплати',
    'contact.guarantee2': 'Результат за 24 години',
    'contact.guarantee3': 'Не підходить - відключаємо безкоштовно',
    'contact.callback': 'Зв\'яжемося протягом 2 годин!',
    'contact.callback.desc': 'Наш експерт подзвонить вам, щоб обговорити ваші потреби та запланувати безкоштовне налаштування першої автоматизації.',
    'contact.questions': 'Є питання? Дзвоніть прямо зараз:',
    'contact.hours': 'Пн-Пт: 9:00 - 18:00 | Сб: 10:00 - 15:00',
    'contact.success.title': 'Дякуємо за заявку!',
    'contact.success.description': 'Ми зв\'яжемося з вами протягом 2 годин, щоб призначити безкоштовну консультацію.',
    'contact.success.bonus': 'Перша автоматизація буде налаштована абсолютно безкоштовно!',

    // FAQ
    'faq.title': 'Часто задавані',
    'faq.subtitle': 'питання',
    'faq.description': 'Відповіді на найважливіші питання про автоматизацію',
    'faq.1.question': 'Чи безпечні мої дані?',
    'faq.1.answer': 'Так, ми використовуємо європейські стандарти GDPR. Всі дані зашифровані та зберігаються на безпечних серверах в Європі. Ми ніколи не передаємо персональні дані клієнтів третім особам.',
    'faq.2.question': 'Скільки часу займе налаштування?',
    'faq.2.answer': 'Базова автоматизація налаштовується протягом 2-4 годин. Більшість процесів працюють уже в перший день. Повне налаштування всіх автоматизацій займає максимум 1 робочий день.',
    'faq.3.question': 'Що якщо автоматизація мені не підійде?',
    'faq.3.answer': 'Перший місяць роботи безкоштовний. Якщо ви не будете задоволені результатами, ми відключимо всі автоматизації безкоштовно. Жодних зобов\'язань чи штрафів.',
    'faq.4.question': 'Чи потрібно змінювати систему запису?',
    'faq.4.answer': 'Ні, ми інтегруємося з будь-якою існуючою системою. Працюємо з Booksy, Fresha, Planity та багатьма іншими. Можете продовжувати користуватися традиційним календарем.',
    'faq.5.question': 'Чи складна автоматизація у використанні?',
    'faq.5.answer': 'Ні, все працює автоматично. Навчання адміністратора займає лише 30 хвилин. Система інтуїтивна і не потребує додаткових технічних знань.',
    'faq.6.question': 'Що входить до щомісячної підтримки?',
    'faq.6.answer': 'Технічна підтримка через WhatsApp, регулярні оновлення системи, консультації з оптимізації процесів, додавання нових автоматизацій та безкоштовне вирішення проблем.',
    'faq.more.title': 'Є інші питання?',
    'faq.more.description': 'Зв\'яжіться з нами напряму - відповімо протягом 30 хвилин',
    'faq.call': 'Дзвоніть: +380 123 456 789',
    'faq.whatsapp': 'Написати в WhatsApp',

    // Footer
    'footer.description': 'Автоматизація процесів для салонів краси. Економимо ваш час і збільшуємо прибуток.',
    'footer.links': 'Швидкі посилання',
    'footer.contact': 'Контакти',
    'footer.hours': 'Години роботи',
    'footer.hours.weekdays': 'Пн-Пт: 9:00 - 18:00',
    'footer.hours.saturday': 'Субота: 10:00 - 15:00',
    'footer.hours.sunday': 'Неділя: Зачинено',
    'footer.consultation': 'Безкоштовна консультація за 24г!',
    'footer.copyright': '© 2025 Beauty Automation. Всі права захищені.',
    'footer.privacy': 'Політика конфіденційності',
    'footer.terms': 'Умови використання',

    // WhatsApp
    'whatsapp.message': 'Привіт! Хотів би дізнатися більше про автоматизацію для мого салону краси.',

    // Common
    'min': 'хв',
    'monthly': 'на місяць',
  },

  en: {
    // Header
    'header.services': 'Services',
    'header.benefits': 'Benefits',
    'header.pricing': 'Pricing',
    'header.testimonials': 'Reviews',
    'header.contact': 'Contact',
    'header.consultation': 'Free Consultation',

    // Hero
    'hero.title': 'Automation for Beauty Salons',
    'hero.subtitle': 'Save 3 hours daily!',
    'hero.description': 'Automatic booking, reminders and client database. More time for clients, less administration.',
    'hero.cta': 'Get Free Setup',
    'hero.demo': 'Watch Demo (2 min)',
    'hero.integrates': 'Integrates with:',

    // Problems
    'problems.title': 'Do you recognize yourself?',
    'problems.subtitle': 'Tired of wasting time on administration?',
    'problems.description': 'Most beauty salon owners face the same problems every day',
    'problems.phone.title': '2-3 hours daily on calls and booking',
    'problems.phone.description': 'Instead of working with clients, you waste time on endless calls to confirm appointments',
    'problems.noshow.title': '30% of clients don\'t show up without reminders',
    'problems.noshow.description': 'Loss of profit due to no-show clients who simply forgot about their appointment',
    'problems.schedule.title': 'Schedule confusion',
    'problems.schedule.description': 'Double bookings, schedule conflicts, unhappy clients',
    'problems.clients.title': 'Losing clients due to slow service',
    'problems.clients.description': 'Clients go to competitors who respond faster',
    'problems.recognize': 'Does this sound familiar?',
    'problems.solution': 'If so, we have a solution for you that automates all these processes and allows you to focus on what matters most - your clients.',
    'problems.see_solution': 'See the solution',

    // Solutions
    'solutions.title': 'We automate all routine processes',
    'solutions.subtitle': 'in 1 day',
    'solutions.description': '5 key automations that will save your time and increase profits',
    'solutions.booking.title': 'Automatic booking',
    'solutions.booking.process': 'Instagram/Facebook → Auto-confirmation → Calendar',
    'solutions.booking.result': '24/7 bookings without your involvement',
    'solutions.reminders.title': 'Smart reminders',
    'solutions.reminders.process': 'Day before visit → SMS/WhatsApp → Confirmation',
    'solutions.reminders.result': '70% reduction in no-shows',
    'solutions.database.title': 'Client database',
    'solutions.database.process': 'Auto-save data → Treatment history → Personalized offers',
    'solutions.database.result': '40% more repeat visits',
    'solutions.reviews.title': 'Automatic reviews',
    'solutions.reviews.process': 'After visit → Review request → Publish to Google/Facebook',
    'solutions.reviews.result': '3x more positive reviews',
    'solutions.analytics.title': 'Profit analytics',
    'solutions.analytics.process': 'Auto-reports → Service analysis → Price recommendations',
    'solutions.analytics.result': '25% profit increase',
    'solutions.cta': 'See how it works',

    // How it works
    'how.title': 'How to launch automation',
    'how.subtitle': 'in your salon',
    'how.description': '3 simple steps to full automation',
    'how.consultation.title': 'Free consultation',
    'how.consultation.description': 'We analyze your processes in 30 minutes',
    'how.consultation.details': 'Show automation possibilities',
    'how.setup.title': 'Setup in 1 day',
    'how.setup.description': 'Integrate with Instagram, WhatsApp, your calendar',
    'how.setup.details': 'Train administrator',
    'how.save.title': 'Save time and money',
    'how.save.description': 'Get 3+ hours of free time daily',
    'how.save.details': 'Increase profit by €500+ monthly',
    'how.start.title': 'Start today!',
    'how.start.description': 'First automation is completely free',
    'how.start.cta': 'Start for free',

    // Results
    'results.title': 'Our clients\' results',
    'results.subtitle': 'in the first month',
    'results.description': 'Real results from real beauty salons',
    'results.noshow': 'fewer no-shows',
    'results.noshow.description': 'Thanks to automatic reminders',
    'results.time': 'hours saved daily',
    'results.time.description': 'More time for client work',
    'results.bookings': 'more bookings',
    'results.bookings.description': 'Automatic request handling 24/7',
    'results.profit': 'additional profit',
    'results.profit.description': 'Due to increased repeat visits',
    'results.roi.title': 'Average ROI: 400% in the first month',
    'results.roi.description': 'Our automations pay for themselves in just 3 weeks',
    'results.roi.cta': 'Calculate your savings',

    // Calculator
    'calculator.title': 'Calculate savings',
    'calculator.subtitle': 'for your salon',
    'calculator.description': 'Interactive calculator shows how much time and money you can save',
    'calculator.params': 'Your salon parameters',
    'calculator.appointments': 'Daily appointments:',
    'calculator.time': 'Time per appointment handling:',
    'calculator.rate': 'Your hourly rate:',
    'calculator.savings': 'Your savings',
    'calculator.daily': 'daily savings',
    'calculator.monthly': 'monthly savings',
    'calculator.payback': 'Automation will pay back in',
    'calculator.payback.weeks': 'weeks',
    'calculator.payback.week': 'week',
    'calculator.payback.then': 'Then it\'s pure savings',
    'calculator.cta': 'I want to save',

    // Pricing
    'pricing.title': 'Package',
    'pricing.subtitle': "'Beauty Automation'",
    'pricing.all_included': '- Everything Included',
    'pricing.description': 'Complete automation solution for your salon',
    'pricing.special': 'SPECIAL OFFER',
    'pricing.standard': 'Standard price',
    'pricing.setup': 'one-time setup',
    'pricing.monthly': 'ongoing support',
    'pricing.save': 'Save 60%',
    'pricing.includes': 'What you get:',
    'pricing.feature1': 'Social media booking automation',
    'pricing.feature2': 'SMS and WhatsApp reminders',
    'pricing.feature3': 'Client database with history',
    'pricing.feature4': 'Automatic reviews',
    'pricing.feature5': 'Analytics and reports',
    'pricing.feature6': 'Administrator training',
    'pricing.feature7': 'WhatsApp technical support',
    'pricing.bonuses': 'Bonuses:',
    'pricing.bonus1': 'First setup FREE (save €200)',
    'pricing.bonus2': 'First month support as gift',
    'pricing.bonus3': 'Personal manager for a month',
    'pricing.cta': 'Get free setup now',
    'pricing.guarantee1': 'No prepayment',
    'pricing.guarantee1.desc': 'Pay only after launch',
    'pricing.guarantee2': 'Results in 24 hours',
    'pricing.guarantee2.desc': 'Quick setup and effects',
    'pricing.guarantee3': 'Doesn\'t fit - we disable for free',
    'pricing.guarantee3.desc': 'Satisfaction guarantee',

    // Testimonials
    'testimonials.title': 'What salon owners say',
    'testimonials.subtitle': 'about our automation',
    'testimonials.description': 'Real reviews from real clients',
    'testimonials.1.name': 'Anna Kowalska',
    'testimonials.1.salon': 'Salon Bella',
    'testimonials.1.text': 'In a month I saved 90 hours on administration. Now I can take 40% more clients!',
    'testimonials.2.name': 'Tomasz Nowak',
    'testimonials.2.salon': 'Beauty Studio',
    'testimonials.2.text': 'No-shows dropped from 30% to 8%. Automation paid for itself in 3 weeks!',
    'testimonials.3.name': 'Katarzyna Zielińska',
    'testimonials.3.salon': 'Glow Salon',
    'testimonials.3.text': 'Clients love WhatsApp reminders. Google rating grew from 4.2 to 4.8!',
    'testimonials.integrations': 'We integrate with the most popular platforms',
    'testimonials.others': 'And many other platforms you already work with',

    // Contact
    'contact.title': 'Get free setup',
    'contact.subtitle': 'of first automation',
    'contact.description': 'Leave a request and we\'ll set up automatic reminders for your salon completely free',
    'contact.name': 'Your name *',
    'contact.name.placeholder': 'Enter your name',
    'contact.phone': 'Phone *',
    'contact.phone.placeholder': '+1 123 456 789',
    'contact.salon': 'Salon name *',
    'contact.salon.placeholder': 'Your salon name',
    'contact.city': 'City *',
    'contact.city.placeholder': 'Enter your city',
    'contact.comment': 'Additional information',
    'contact.comment.placeholder': 'Describe your needs or ask a question...',
    'contact.submit': 'Get free automation',
    'contact.guarantees': 'Guarantees under form:',
    'contact.guarantee1': 'No prepayment',
    'contact.guarantee2': 'Results in 24 hours',
    'contact.guarantee3': 'Doesn\'t fit - we disable for free',
    'contact.callback': 'We\'ll contact you within 2 hours!',
    'contact.callback.desc': 'Our expert will call you to discuss your needs and plan free setup of first automation.',
    'contact.questions': 'Have questions? Call right now:',
    'contact.hours': 'Mon-Fri: 9:00 - 18:00 | Sat: 10:00 - 15:00',
    'contact.success.title': 'Thank you for your request!',
    'contact.success.description': 'We\'ll contact you within 2 hours to schedule a free consultation.',
    'contact.success.bonus': 'First automation will be set up completely free!',

    // FAQ
    'faq.title': 'Frequently asked',
    'faq.subtitle': 'questions',
    'faq.description': 'Answers to the most important questions about automation',
    'faq.1.question': 'Is my data safe?',
    'faq.1.answer': 'Yes, we use European GDPR standards. All data is encrypted and stored on secure servers in Europe. We never share personal client data with third parties.',
    'faq.2.question': 'How long does setup take?',
    'faq.2.answer': 'Basic automation is set up within 2-4 hours. Most processes work from day one. Full setup of all automations takes maximum 1 business day.',
    'faq.3.question': 'What if automation doesn\'t suit me?',
    'faq.3.answer': 'First month of work is free. If you\'re not satisfied with results, we\'ll disable all automations for free. No obligations or penalties.',
    'faq.4.question': 'Do I need to change my booking system?',
    'faq.4.answer': 'No, we integrate with any existing system. We work with Booksy, Fresha, Planity and many others. You can continue using traditional calendar.',
    'faq.5.question': 'Is automation complicated to use?',
    'faq.5.answer': 'No, everything works automatically. Administrator training takes only 30 minutes. System is intuitive and requires no additional technical knowledge.',
    'faq.6.question': 'What\'s included in monthly support?',
    'faq.6.answer': 'Technical support via WhatsApp, regular system updates, process optimization consultations, adding new automations and free problem solving.',
    'faq.more.title': 'Have other questions?',
    'faq.more.description': 'Contact us directly - we\'ll respond within 30 minutes',
    'faq.call': 'Call: +1 123 456 789',
    'faq.whatsapp': 'Write on WhatsApp',

    // Footer
    'footer.description': 'Process automation for beauty salons. We save your time and increase profits.',
    'footer.links': 'Quick links',
    'footer.contact': 'Contact',
    'footer.hours': 'Working hours',
    'footer.hours.weekdays': 'Mon-Fri: 9:00 - 18:00',
    'footer.hours.saturday': 'Saturday: 10:00 - 15:00',
    'footer.hours.sunday': 'Sunday: Closed',
    'footer.consultation': 'Free consultation in 24h!',
    'footer.copyright': '© 2025 Beauty Automation. All rights reserved.',
    'footer.privacy': 'Privacy Policy',
    'footer.terms': 'Terms of Service',

    // WhatsApp
    'whatsapp.message': 'Hi! I would like to learn more about automation for my beauty salon.',

    // Common
    'min': 'min',
    'monthly': 'monthly',
  }
};

interface LanguageProviderProps {
  children: ReactNode;
}

export const LanguageProvider: React.FC<LanguageProviderProps> = ({ children }) => {
  const [language, setLanguage] = useState<Language>('pl');

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};

export const useLanguage = (): LanguageContextType => {
  const context = useContext(LanguageContext);
  if (!context) {
    throw new Error('useLanguage must be used within a LanguageProvider');
  }
  return context;
};